//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPRE.Resources.ROMToolboxDB {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BDHCAMPatchDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BDHCAMPatchDB() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSPRE.Resources.ROMToolboxDB.BDHCAMPatchDB", typeof(BDHCAMPatchDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B6 F3 2E FA.
        /// </summary>
        internal static string branchCode_HG {
            get {
                return ResourceManager.GetString("branchCode_HG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B9 F3 E2 F8.
        /// </summary>
        internal static string branchCode_Plat_ENG {
            get {
                return ResourceManager.GetString("branchCode_Plat_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B9 F3 AA F8.
        /// </summary>
        internal static string branchCode_Plat_ESP {
            get {
                return ResourceManager.GetString("branchCode_Plat_ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] cpue_cam {
            get {
                object obj = ResourceManager.GetObject("cpue_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] cpus_cam {
            get {
                object obj = ResourceManager.GetObject("cpus_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] ipge_cam {
            get {
                object obj = ResourceManager.GetObject("ipge_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] ipgs_cam {
            get {
                object obj = ResourceManager.GetObject("ipgs_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] ipke_cam {
            get {
                object obj = ResourceManager.GetObject("ipke_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] ipks_cam {
            get {
                object obj = ResourceManager.GetObject("ipks_cam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 00 4B 18 47 41 9C 3D 02.
        /// </summary>
        internal static string overlayCode1 {
            get {
                return ResourceManager.GetString("overlayCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 00 4B 18 47 01 9C 3D 02.
        /// </summary>
        internal static string overlayCode2 {
            get {
                return ResourceManager.GetString("overlayCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 71088.
        /// </summary>
        internal static string subroutineOffset {
            get {
                return ResourceManager.GetString("subroutineOffset", resourceCulture);
            }
        }
    }
}
