using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DSPRE {
    public static class PokeDatabase {
        public static class Area {
            public static string[] PtAreaIconValues = new string[] {
                "[00] City",
                "[01] City",
                "[02] Town 1",
                "[03] Town 2",
                "[04] Cave",
                "[05] Forest",
                "[06] Water",
                "[07] Field",
                "[08] Island",
                "[09] Wood"
            };
            public static string[] HGSSAreaIconValues = new string[] {
                "[002] Wood",
                "[009] Gray",
                "[017] Wall",
                "[048] Not displayed",
                "[131] Town",
                "[132] Cave",
                "[135] Field",
                "[152] Lake",
                "[165] Forest",
                "[166] Water"
            };
            public static string[] HGSSAreaProperties = new string[] {
                "[00] Unknown",
                "[01] Unknown",
                "[02] Unknown",
                "[03] Cave Animation",
                "[04] Hide Location Tag",
                "[05] Unknown",
                "[06] Unknown",
                "[07] Unknown",
                "[08] Unknown",
                "[09] Unknown",
                "[10] Unknown",
                "[11] Unknown",
                "[12] Unknown",
                "[13] Unknown",
                "[14] Unknown",
                "[15] Unknown",
                "[16] Unknown",
            };
        }
        public static class ShowName {
            public static string[] DPShowNameValues = new string[] {
                "[000] Show",
                "[001] Show",
                "[002] Show",
                "[003] Show",
                "[004] Don't show"
            };
            public static string[] PtShowNameValues = new string[] {
                "[000] Show",
                "[001] Show",
                "[002] Show",
                "[003] Show",
                "[004] Don't show",
                "[128] Don't show",
                "[129] Show",
                "[130] Show",
                "[131] Show",
                "[132] Don't show",
                "[134] Show"
            };
        }
        public static class Weather {
            public static Dictionary<int, string> DPWeatherDict = new Dictionary<int, string> {
                [00] = "Normal",
                [01] = "Normal, somewhat dark",
                [02] = "Rain",
                [03] = "Heavy rain",
                [04] = "Thunderstorm",
                [05] = "Snowfall, slow",
                [06] = "Diamond dust",
                [07] = "Blizzard",
                [09] = "Volcanic ash fall, slow",
                [10] = "Sand storm",
                [11] = "Hail",
                [12] = "Rocks ascending (?)",
                [14] = "Fog",
                [15] = "Deep fog",
                [16] = "Dark, Flash usable",
                [17] = "Lightning, no rain",
                [22] = "Volcanic ash fall, steady",
            };
            public static Dictionary<int, string> PtWeatherDict = new Dictionary<int, string> {
                [00] = "Normal",
                [01] = "Normal, somewhat dark",
                [02] = "Rain",
                [03] = "Heavy rain",
                [04] = "Thunderstorm",
                [05] = "Snowfall, slow",
                [06] = "Diamond dust",
                [07] = "Blizzard",
                [09] = "Volcanic ash fall, slow",
                [10] = "Sand storm",
                [11] = "Hail",
                [12] = "Rocks ascending (?)",
                [14] = "Fog",
                [15] = "Deep fog",
                [16] = "Dark, Flash usable",
                [17] = "Lightning, no rain",
                [22] = "Volcanic ash fall, steady",
                [23] = "Eterna forest weather",
                [24] = "Player in circle of light",
                [25] = "Player in a circle of light",
            };
            public static Dictionary<int, string> HGSSWeatherDict = new Dictionary<int, string> {
                [00] = "Normal",
                [01] = "Normal [1]",

                [02] = "Rain",
                [03] = "Rain [3]",
                [04] = "Rain [4]",
                [05] = "Rain [5]",
                [06] = "Rain [6]",
                [07] = "Rain [7]",
                [08] = "Rain [8]",

                [09] = "Snow [9]",
                [10] = "Snow [10]",
                [11] = "Snow [11]",
                [12] = "Snow [12]",
                [13] = "Snow [13]",
                [14] = "Sandstorm (in battle only)",
                [15] = "Snow [15]",

                [16] = "Diamond Dust",
                [17] = "Diamond Dust [17]",

                [18] = "Fog",
                [19] = "Fog [19]",
                [20] = "Fog [20]",
                [21] = "Fog [21]",

                [22] = "Darkness",
                [23] = "Darkness [23]",
                [24] = "Darkness after flash",
                [25] = "Darkness after flash [25]",
                [26] = "Low Light (Battle Arcade)"
            };
        }
        public static class CameraAngles {
            public static string[] DPPtCameraValues = new string[] {
                "[00] 3D Normal",
                "[01] 3D Top View (Higher than [12])",
                "[02] 3D Frontal Low (Wider than [15])",
                "[03] 3D Frontal",
                "[04] 2D Ortho",
                "[05] 3D Normal - Wide FOV",
                "[06] 3D Bird View",
                "[07] 3D Normal",
                "[08] 3D Bird View Far",
                "[09] 3D Frontal - Wide FOV",
                "[10] 3D Top View - Narrow",
                "[11] Normal 3D",
                "[12] 3D Top View",
                "[13] Frontal 3D",
                "[14] 3D Top View - Wide FOV",
                "[15] 3D Frontal Low"
            };
            public static string[] HGSSCameraValues = new string[] {
                "[00] 3D Top",
                "[01] 3D Front High",
                "[02] 3D Lower",
                "[03] 3D Frontal",
                "[04] 2D Top View",
                "[05] Normal 3D",
                "[06] 3D Normal",
                "[07] High 3D",
                "[08] 3D Top View",
                "[09] 3D Top View",
                "[10] 3D High Wide",
                "[11] 3D Frontal Wide",
                "[12] 3D Lower Close",
                "[13] 3D Full Frontal",
                "[14] 3D Top View",
                "[15] 2D Higher"
            };
        }
        public abstract class MusicDB {
            public static Dictionary<ushort, string> DPMusicDict = new Dictionary<ushort, string>() {
                [1000] = "Mystery Zone",
                [1001] = "Silence",
                [1002] = "Pal Park",
                [1004] = "Twinleaf Town (Day)",
                [1005] = "Sandgem Town (Day)",
                [1006] = "Floaroma Town (Day)",
                [1008] = "Route 225 (Day)",
                [1009] = "Valor Lakefront (Day)",
                [1010] = "Jubilife City (Day)",
                [1011] = "Canalave City (Day)",
                [1012] = "Oreburgh City (Day)",
                [1013] = "Eterna City (Day)",
                [1014] = "Hearthome City (Day)",
                [1015] = "Pastoria City (Day)",
                [1016] = "Veilstone City (Day)",
                [1017] = "Sunyshore City (Day)",
                [1018] = "Snowpoint City (Day)",
                [1019] = "Pokémon League (Day)",
                [1020] = "Fight Area (Day)",
                [1021] = "Route 201 (Day)",
                [1022] = "Route 203 (Day)",
                [1023] = "Route 205 (Day)",
                [1024] = "Route 206 (Day)",
                [1025] = "Route 209 (Day)",
                [1026] = "Route 215 (Day)",
                [1027] = "Route 216 (Day)",
                [1028] = "Route 228 (Day)",
                [1033] = "Twinleaf Town (Night)",
                [1034] = "Sandgem Town (Night)",
                [1035] = "Floaroma Town (Night)",
                [1037] = "Route 225 (Night)",
                [1038] = "Valor Lakefront (Night)",
                [1039] = "Jubilife City (Night)",
                [1040] = "Canalave City (Night)",
                [1041] = "Oreburgh City (Night)",
                [1042] = "Eterna City (Night)",
                [1043] = "Hearthome CIty (Night)",
                [1044] = "Pastoria City (Night)",
                [1045] = "Veilstone City (Night)",
                [1046] = "Sunyshore City (Night)",
                [1047] = "Snowpoint City (Night)",
                [1048] = "Pokémon League (Night)",
                [1049] = "Fight Area (Night)",
                [1050] = "Route 201 (Night)",
                [1051] = "Route 203 (Night)",
                [1052] = "Route 205 (Night)",
                [1053] = "Route 206 (Night)",
                [1054] = "Route 209 (Night)",
                [1055] = "Route 215 (Night)",
                [1056] = "Route 216 (Night)",
                [1057] = "Route 228 (Night)",
                [1060] = "Mystery Zone",
                [1062] = "Victory Road",
                [1063] = "Eterna Forest",
                [1064] = "Old Chateau",
                [1065] = "Cavern on the Lake",
                [1066] = "Amity Square",
                [1067] = "Team Galactic HQ",
                [1068] = "Eterna Galactic building",
                [1069] = "Great Marsh",
                [1070] = "Lake theme (Day)",
                [1071] = "Mt. Coronet",
                [1072] = "Spear Pillar",
                [1073] = "Stark Mountain (inside)",
                [1074] = "Cave 1",
                [1075] = "Cave 2",
                [1076] = "Elite 4 - Showdown",
                [1077] = "Hall of Fame",
                [1085] = "Pokémon Center (Day)",
                [1086] = "Pokémon Center (Night)",
                [1087] = "Gym theme",
                [1088] = "Rowan's Lab",
                [1089] = "Poffin House",
                [1090] = "Pokémon Mart",
                [1091] = "Game Corner",
                [1092] = "Battle Tower (inside)",
                [1093] = "Jubilife TV",
                [1094] = "Team Galactic Lab",
                [1096] = "Hall of Origin",
                [1097] = "GTS theme"
            };
            public static Dictionary<ushort, string> PtMusicDict = new Dictionary<ushort, string>() {
                [1000] = "Mystery Zone",
                [1001] = "Silence",
                [1002] = "Pal Park",
                [1004] = "Twinleaf Town (Day)",
                [1005] = "Sandgem Town (Day)",
                [1006] = "Floaroma Town (Day)",
                [1008] = "Route 225 (Day)",
                [1009] = "Valor Lakefront (Day)",
                [1010] = "Jubilife City (Day)",
                [1011] = "Canalave City (Day)",
                [1012] = "Oreburgh City (Day)",
                [1013] = "Eterna City (Day)",
                [1014] = "Hearthome City (Day)",
                [1015] = "Pastoria City (Day)",
                [1016] = "Veilstone City (Day)",
                [1017] = "Sunyshore City (Day)",
                [1018] = "Snowpoint City (Day)",
                [1019] = "Pokémon League (Day)",
                [1020] = "Fight Area (Day)",
                [1021] = "Route 201 (Day)",
                [1022] = "Route 203 (Day)",
                [1023] = "Route 205 (Day)",
                [1024] = "Route 206 (Day)",
                [1025] = "Route 209 (Day)",
                [1026] = "Route 215 (Day)",
                [1027] = "Route 216 (Day)",
                [1028] = "Route 228 (Day)",
                [1033] = "Twinleaf Town (Night)",
                [1034] = "Sandgem Town (Night)",
                [1035] = "Floaroma Town (Night)",
                [1037] = "Route 225 (Night)",
                [1038] = "Valor Lakefront (Night)",
                [1039] = "Jubilife City (Night)",
                [1040] = "Canalave City (Night)",
                [1041] = "Oreburgh City (Night)",
                [1042] = "Eterna City (Night)",
                [1043] = "Hearthome CIty (Night)",
                [1044] = "Pastoria City (Night)",
                [1045] = "Veilstone City (Night)",
                [1046] = "Sunyshore City (Night)",
                [1047] = "Snowpoint City (Night)",
                [1048] = "Pokémon League (Night)",
                [1049] = "Fight Area (Night)",
                [1050] = "Route 201 (Night)",
                [1051] = "Route 203 (Night)",
                [1052] = "Route 205 (Night)",
                [1053] = "Route 206 (Night)",
                [1054] = "Route 209 (Night)",
                [1055] = "Route 215 (Night)",
                [1056] = "Route 216 (Night)",
                [1057] = "Route 228 (Night)",
                [1060] = "Mystery Zone",
                [1062] = "Victory Road",
                [1063] = "Eterna Forest",
                [1064] = "Old Chateau",
                [1065] = "Cavern on the Lake",
                [1066] = "Amity Square",
                [1067] = "Team Galactic HQ",
                [1068] = "Galactic Eterna Building",
                [1069] = "Great Marsh",
                [1070] = "Lake theme (Day)",
                [1071] = "Mt. Coronet",
                [1072] = "Spear Pillar",
                [1073] = "Stark Mountain (in)",
                [1074] = "Cave 1",
                [1075] = "Cave 2",
                [1076] = "Elite 4 - Showdown",
                [1077] = "Hall of Fame",
                [1085] = "Pokémon Center (Day)",
                [1086] = "Pokémon Center (Night)",
                [1087] = "Gym theme",
                [1088] = "Rowan's Lab",
                [1089] = "Poffin House",
                [1090] = "Pokémon Mart",
                [1091] = "Game Corner",
                [1092] = "Battle Tower (inside)",
                [1093] = "Jubilife TV",
                [1094] = "Team Galactic Lab",
                [1096] = "Hall of Origin",
                [1097] = "GTS theme",
                [1190] = "Distortion World",
                [1191] = "Battle Arcade",
                [1192] = "Battle Hall",
                [1193] = "Battle Castle",
                [1194] = "Battle Factory",
                [1195] = "Battle Factory",
                [1196] = "Global Terminal"
            };
            public static Dictionary<ushort, string> HGSSMusicDict = new Dictionary<ushort, string>() {
                [1000] = "Mystery Zone",
                [1001] = "Silence [Outside]",
                [1002] = "Silence [Dungeon]",
                [1004] = "Opening Theme",
                [1008] = "Title Screen Theme",
                [1013] = "Bicycle Theme",
                [1018] = "New Bark Town",
                [1019] = "Cherrygrove City",
                [1020] = "Violet City",
                [1021] = "Azalea Town",
                [1022] = "Goldenrod City",
                [1023] = "Ecruteak City",
                [1024] = "Olivine City",
                [1025] = "Cianwood City",
                [1026] = "Mahogany Town",
                [1027] = "Blackthorn City",
                [1028] = "Route 29",
                [1029] = "Route 30/31",
                [1030] = "Route 32",
                [1031] = "Route 33",
                [1032] = "Route 34",
                [1033] = "Route 35/36/37",
                [1034] = "Route 40/41",
                [1035] = "Route 45/46",
                [1036] = "Route 38/39",
                [1037] = "Route 42/43/44",
                [1038] = "Vermillion City",
                [1039] = "Saffron City",
                [1040] = "Cerulean City",
                [1041] = "Lavender Town",
                [1042] = "Celadon City",
                [1043] = "Fuchsia City",
                [1044] = "Pewter City",
                [1045] = "Viridian City",
                [1046] = "Pallet Town",
                [1047] = "Cinnabar Island",
                [1050] = "Route 1",
                [1051] = "Route 2/22",
                [1052] = "Route 6",
                [1053] = "Route 4/5/9/10",
                [1054] = "Route 8/10",
                [1055] = "Route 7/16",
                [1056] = "Route 18/19/20",
                [1057] = "Route 3",
                [1058] = "Route 20/21",
                [1059] = "Route 11",
                [1060] = "Route 12/13/14/15",
                [1061] = "Route 24/25",
                [1062] = "Route 26/27",
                [1063] = "Pokémon Center",
                [1064] = "Pokémon Mart",
                [1065] = "Gym theme",
                [1066] = "Prof. Elm Lab",
                [1068] = "Kimono Girls Theater",
                [1069] = "Game Corner",
                [1070] = "Battle Frontier",
                [1071] = "Battle Tower",
                [1072] = "Sprout Tower",
                [1073] = "Ilex Forest",
                [1074] = "Ruins of Alph",
                [1075] = "National Park",
                [1076] = "Burned Tower",
                [1077] = "Bell Tower",
                [1078] = "Lighthouse",
                [1079] = "Team Rocket HQ",
                [1080] = "Ice Path",
                [1081] = "Dragon's Den",
                [1082] = "Diglett's Cave",
                [1083] = "Viridian Forest",
                [1084] = "Victory Road",
                [1085] = "Indigo Plateau",
                [1092] = "PokéAthlon Game",
                [1096] = "S.S. Aqua",
                [1097] = "Mt. Moon Plaza",
                [1099] = "Sleeping Radio Music",
                [1100] = "Pokemon March Radio",
                [1101] = "Unown Radio",
                [1102] = "Pokeflute Radio",
                [1103] = "Prof. Oak's Theme/Radio",
                [1134] = "Pokéathlon Dome (In)",
                [1141] = "Pokéathlon Dome (Out)",
                [1143] = "Battle Factory",
                [1144] = "Battle Hall",
                [1145] = "Battle Arcade",
                [1146] = "Battle Castle",
                [1151] = "Wi-Fi Union Room",
                [1153] = "WiFi Plaza Parade",
                [1154] = "GTS Terminal",
                [1155] = "Spin Trade Theme",
                [1157] = "Route 47/48",
                [1158] = "Safari Zone Gate",
                [1159] = "Pal Park",
                [1160] = "Ethan's Theme",
                [1161] = "Lyra's Theme",
                [1163] = "Kimono Girls Ritual",
                [1164] = "Kimono Girls Theme",
                [1165] = "Battle! Ho-Oh!",
                [1166] = "Battle! Lugia",
                [1166] = "Spiky-Eared Pichu",
                [1168] = "Sinjoh Ruins",
                [1169] = "Route 101 Radio",
                [1170] = "Route 201 Radio",
                [1171] = "Gym Theme [Radio]",
                [1172] = "Azalea Town [Radio]",
                [1172] = "Goldenrod City [Radio]",
                [1173] = "Battle! Kyogre/Groudon",
                [1175] = "PokéWalker Theme",
                [1176] = "Battle! Arceus (Event)",
                [1216] = "Route 17"
            };
        }
        public static class ScriptMovements {
            public static string[] moveArray = new string[] {
                "[00]  None",
                "[01]  None",
                "[02]  Looking in all directions",
                "[03]  Walking around in all directions",
                "[04]  Walking Up, Down",
                "[05]  Walking Left, Right",
                "[06]  Looking Up, Left",
                "[07]  Looking Up, Right",
                "[08]  Looking Down, Left",
                "[09]  Looking Down, Right",
                "[10]  Looking Up, Down, Left",
                "[11]  Looking Up, Right, Down",
                "[12]  Looking Right, Left, Up",
                "[13]  Looking Right, Left, Down",
                "[14]  Facing Up",
                "[15]  Facing Down",
                "[16]  Facing Left",
                "[17]  Facing Right",
                "[18]  Counterclockwise spinning",
                "[19]  Clockwise spinning",
                "[20]  Running Up, Down",
                "[21]  L Run (Up, Right)",
                "[22]  Patrols Area, then stops",
                "[23]  Patrols Area, then stops",
                "[24]  L Run (Up, Right)",
                "[25]  Patrols Area, then stops",
                "[26]  Patrols Area, then stops",
                "[27]  Patrols Area, then stops",
                "[28]  L run (Right, Down)",
                "[29]  L run (Left, Up)",
                "[30]  Continuous patrolling",
                "[31]  Continuous patrolling",
                "[32]  L Run (Down, Right)",
                "[33]  L Run (Right, Up)",
                "[34]  Patrols Area, then stops",
                "[35]  Patrols Area, then stops",
                "[36]  L Run (Down, Left)",
                "[37]  Running Up, Left, Down, Right",
                "[38]  Running Down, Right, Up, Left",
                "[39]  Running Left, Down, Right, Up",
                "[40]  Running Right, Up, Left, Down",
                "[41]  Running Up, Right, Down, Left",
                "[42]  Running Down, Left, Up, Right",
                "[43]  Running Left, Up, Right, Down",
                "[44]  Running Right, Down, Left, Up",
                "[45]  Looking Up, Down",
                "[46]  Looking Right, Left",
                "[47]  ?",
                "[48]  Follow Hero",
                "[49]  Semi-circle spin (Down, Right, Up)",
                "[50]  ?",
                "[51]  Hidden Under Snow",
                "[52]  Hidden Under Snow",
                "[53]  Hidden Underground",
                "[54]  Hidden Under Grass",
                "[55]  Mimicks Player (moves within range)",
                "[56]  Mimicks Player (moves within range)",
                "[57]  Mimicks Player (moves within range)",
                "[58]  Mimicks Player (moves within range)",
                "[59]  Mimick's Player facing direction",
                "[60]  Mimick's Player facing direction",
                "[61]  Mimick's Player facing direction",
                "[62]  Mimick's Player facing direction",
                "[63]  Jogging on the spot",
                "[64]  Jogging on the spot",
                "[65]  Jogging on the spot",
                "[66]  Jogging on the spot",
                "[67]  Walking Right, Left",
                "[68]  Looking Right",
                "[69]  ?",
                "[70]  ?",
                "[71]  Looking Left"
            };
        }
        public static class System {
            public static class Scripts {
                public static Dictionary<byte, string> byteToComparisonOperatorDict = new Dictionary<byte, string>() {
                    [0x0] = "LOWER",
                    [0x1] = "EQUAL",
                    [0x2] = "LARGER",
                    [0x3] = "LOWER/EQUAL",
                    [0x4] = "LARGER/EQUAL",
                    [0x5] = "DIFFERENT",
                    [0x6] = "OR",
                    [0x7] = "AND",
                    [0xFF] = "TRUEUP"
                };
                public static Dictionary<string, byte> stringToComparisonOperatorDict = new Dictionary<string, byte>() {
                    ["LOWER"] = 0x0,
                    ["EQUAL"] = 0x1,
                    ["LARGER"] = 0x2,
                    ["LOWER/EQUAL"] = 0x3,
                    ["LARGER/EQUAL"] = 0x4,
                    ["DIFFERENT"] = 0x5,
                    ["OR"] = 0x6,
                    ["AND"] = 0x7,
                    ["TRUEUP"] = 0xFF
                };
                public static Dictionary<string, ushort> commandsDictDPPt = new Dictionary<string, ushort>() {
                    ["Nop"] = 0x0000,
                    ["Dummy"] = 0x0001,
                    ["End"] = 0x0002,
                    ["TimeWait"] = 0x0003,
                    ["CompareVarValue"] = 0x0011,
                    ["CompareVars"] = 0x0012,
                    ["CommonScript"] = 0x0014,
                    ["Jump"] = 0x0016,
                    ["Call"] = 0x001A,
                    ["Return"] = 0x001B,
                    ["Jump-If"] = 0x001C,
                    ["Call-If"] = 0x001D,
                    ["SetFlag"] = 0x001E,
                    ["ClearFlag"] = 0x001F,
                    ["CheckFlag"] = 0x0020,
                    ["SetValue"] = 0x0023,
                    ["CompareVarsToByte"] = 0x0026,
                    ["SetVar"] = 0x0028,
                    ["CopyVar"] = 0x0029,
                    ["Message"] = 0x002C,
                    ["Message2"] = 0x002D,
                    ["Message3"] = 0x002F,
                    ["WaitButton"] = 0x0031,
                    ["CloseMessage"] = 0x0034,
                    ["FreezeMessageBox"] = 0x0035,
                    ["CallMessageBox"] = 0x0036,
                    ["ColorMessageBox"] = 0x0037,
                    ["TypeMessageBox"] = 0x0038,
                    ["NoMapMessageBox"] = 0x0039,
                    ["CallMessageBoxText"] = 0x003A,
                    ["Menu"] = 0x003C,
                    ["YesNoBox"] = 0x003E,
                    ["WaitFor"] = 0x003F,
                    ["Multi"] = 0x0040,
                    ["Multi2"] = 0x0041,
                    ["TextScriptMulti"] = 0x0042,
                    ["CloseMulti"] = 0x0043,
                    ["Multi3"] = 0x0044,
                    ["TextMessageScript"] = 0x0046,
                    ["MultiRow"] = 0x0048,
                    ["PlayFanfare"] = 0x0049,
                    ["PlayFanfare2"] = 0x004A,
                    ["WaitFanfare"] = 0x004B,
                    ["PlayCry"] = 0x004C,
                    ["WaitCry"] = 0x004D,
                    ["PlaySound"] = 0x004E,
                    ["FadeDefaultMusic"] = 0x004F,
                    ["PlayMusic"] = 0x0050,
                    ["StopMusic"] = 0x0051,
                    ["RestartMusic"] = 0x0052,
                    ["SwitchMusic"] = 0x0054,
                    ["SwitchMusic2"] = 0x005A,
                    ["ApplyMovement"] = 0x005E,
                    ["WaitMovement"] = 0x005F,
                    ["LockAll"] = 0x0060,
                    ["ReleaseAll"] = 0x0061,
                    ["Lock"] = 0x0062,
                    ["Release"] = 0x0063,
                    ["AddOW"] = 0x0064,
                    ["RemoveOW"] = 0x0065,
                    ["LockCam"] = 0x0066,
                    ["FacePlayer"] = 0x0068,
                    ["CheckSpritePosition"] = 0x0069,
                    ["CheckPersonPosition"] = 0x006B,
                    ["ContinueFollow"] = 0x006C,
                    ["FollowHero"] = 0x006D,
                    ["StopFollowHero"] = 0x006E,
                    ["GiveMoney"] = 0x006F,
                    ["TakeMoney"] = 0x0070,
                    ["CheckMoney"] = 0x0071,
                    ["ShowMoney"] = 0x0072,
                    ["HideMoney"] = 0x0073,
                    ["UpdateMoney"] = 0x0074,
                    ["ShowCoins"] = 0x0075,
                    ["HideCoins"] = 0x0076,
                    ["UpdateCoins"] = 0x0077,
                    ["CheckCoins"] = 0x0078,
                    ["GiveCoins"] = 0x0079,
                    ["TakeCoins"] = 0x007A,
                    ["TakeItem"] = 0x007B,
                    ["CheckStoreItem"] = 0x007C,
                    ["CheckItem"] = 0x007D,
                    ["CheckUndergroundPCStatus"] = 0x0085,
                    ["CheckPokémonParty"] = 0x0093,
                    ["StorePokémonParty"] = 0x0094,
                    ["SetPokémonPartyStored"] = 0x0095,
                    ["GivePokémon"] = 0x0096,
                    ["GiveEgg"] = 0x0097,
                    ["CheckMove"] = 0x0099,
                    ["CheckPlaceStored"] = 0x009A,
                    ["CallEnd"] = 0x00A1,
                    ["WFC"] = 0x00A3,
                    ["Interview"] = 0x00A5,
                    ["DressPokémon"] = 0x00A6,
                    ["DisplayDressedPokémon"] = 0x00A7,
                    ["DisplayContestPokémon"] = 0x00A8,
                    ["CapsuleEditor"] = 0x00A9,
                    ["SinnohMaps"] = 0x00AA,
                    ["BoxPokémon"] = 0x00AB,
                    ["DrawUnion"] = 0x00AC,
                    ["TrainerCaseUnion"] = 0x00AD,
                    ["TradeUnion"] = 0x00AE,
                    ["RecordMixingUnion"] = 0x00AF,
                    ["EndGame"] = 0x00B0,
                    ["HallOfFameData"] = 0x00B1,
                    ["WFC1"] = 0x00B3,
                    ["ChooseStarter"] = 0x00B4,
                    ["ChoosePlayerName"] = 0x00BA,
                    ["ChoosePokémonName"] = 0x00BB,
                    ["FadeScreen"] = 0x00BC,
                    ["ResetScreen"] = 0x00BD,
                    ["Warp"] = 0x00BE,
                    ["RockClimbAnimation"] = 0x00BF,
                    ["SurfAnimation"] = 0x00C0,
                    ["WaterfallAnimation"] = 0x00C1,
                    ["FlyAnimation"] = 0x00C2,
                    ["Tuxedo"] = 0x00C6,
                    ["CheckBike"] = 0x00C7,
                    ["RideBike"] = 0x00C8,
                    ["BerryHeroAnimation"] = 0x00CB,
                    ["StopBerryHeroAnimation"] = 0x00CC,
                    ["SetVariableHero"] = 0x00CD,
                    ["SetVariableRival"] = 0x00CE,
                    ["SetVariableAlter"] = 0x00CF,
                    ["SetVariablePokémon"] = 0x00D0,
                    ["SetVariableItem"] = 0x00D1,
                    ["SetVariableAttackItem"] = 0x00D3,
                    ["SetVariableAttack"] = 0x00D4,
                    ["SetVariableNumber"] = 0x00D5,
                    ["SetVariableNickname"] = 0x00D6,
                    ["SetVariableObject"] = 0x00D7,
                    ["SetVariableTrainer"] = 0x00D8,
                    ["SetVarPokémonStored"] = 0x00DA,
                    ["SetVarHeroStored"] = 0x00DB,
                    ["SetVarRivalStored"] = 0x00DC,
                    ["SetVarAlterStored"] = 0x00DD,
                    ["StoreStarter"] = 0x00DE,
                    ["TrainerBattle"] = 0x00E5,
                    ["EndTrainerBattle"] = 0x00E6,
                    ["ActLeagueBattlers"] = 0x00EA,
                    ["LostGoToPokémonCenter"] = 0x00EB,
                    ["CheckLost"] = 0x00EC,
                    ["ChooseFriend"] = 0x00F2,
                    ["WirelessBattleWait"] = 0x00F3,
                    ["PokémonContest"] = 0x00F7,
                    ["FlashContest"] = 0x0111,
                    ["EndFlash"] = 0x0112,
                    ["ShowLinkCountRecord"] = 0x0116,
                    ["WarpMapElevator"] = 0x011B,
                    ["CheckFloor"] = 0x011C,
                    ["SetPositionAfterShip"] = 0x0120,
                    ["WildBattle"] = 0x0124,
                    ["StarterBattle"] = 0x0125,
                    ["ExplanationBattle"] = 0x0126,
                    ["HoneyTreeBattle"] = 0x0127,
                    ["RandomBattle"] = 0x0129,
                    ["WriteAutograph"] = 0x012B,
                    ["CheckDress"] = 0x012E,
                    ["GivePokétch"] = 0x0131,
                    ["ActivatePokétchApp"] = 0x0133,
                    ["StorePokétchApp"] = 0x0134,
                    ["ExpectDecisionOther"] = 0x0143,
                    ["PokéMart"] = 0x0147,
                    ["PokéMart1"] = 0x0148,
                    ["PokéMart2"] = 0x0149,
                    ["PokéMart3"] = 0x014A,
                    ["DefeatGoToPokéCenter"] = 0x014B,
                    ["CheckGender"] = 0x014D,
                    ["HealPokémon"] = 0x014E,
                    ["UnionRoom"] = 0x0153,
                    ["ActivatePokédex"] = 0x0158,
                    ["GiveRunningShoes"] = 0x015A,
                    ["CheckBadge"] = 0x015B,
                    ["EnableBadge"] = 0x015C,
                    ["DisableBadge"] = 0x015D,
                    ["PrepareDoorAnimation"] = 0x0168,
                    ["WaitAction"] = 0x0169,
                    ["WaitClose"] = 0x016A,
                    ["OpenDoor"] = 0x016B,
                    ["CloseDoor"] = 0x016C,
                    ["CheckPartyNumber"] = 0x0177,
                    ["OpenBerryPouch"] = 0x0178,
                    ["SetOverworldPosition"] = 0x0186,
                    ["SetOverworldMovement"] = 0x0188,
                    ["ReleaseOverworld"] = 0x0189,
                    ["SetDoorPassable"] = 0x018A,
                    ["SetDoorLocked"] = 0x018B,
                    ["ShowSavingClock"] = 0x018D,
                    ["HideSavingClock"] = 0x018E,
                    ["ChoosePokémonMenu"] = 0x0191,
                    ["ChoosePokémonMenu2"] = 0x0192,
                    ["StorePokémonMenu2"] = 0x0193,
                    ["PokémonInfo"] = 0x0195,
                    ["StorePokémonNumber"] = 0x0198,
                    ["CheckPartyNumber2"] = 0x019A,
                    ["EggAnimation"] = 0x01AC,
                    ["MailBox"] = 0x01B3,
                    ["RecordList"] = 0x01B5,
                    ["CheckHappiness"] = 0x01B9,
                    ["CheckPosition"] = 0x01BD,
                    ["CheckPokémonParty2"] = 0x01C0,
                    ["CopyPokémonHeight"] = 0x01C1,
                    ["SetVariablePokémonHeight"] = 0x01C2,
                    ["ComparePokémonHeight"] = 0x01C3,
                    ["CheckPokémonHeight"] = 0x01C4,
                    ["MoveInfo"] = 0x01C6,
                    ["StoreMove"] = 0x01C7,
                    ["DeleteMove"] = 0x01C9,
                    ["BerryPoffin"] = 0x01D7,
                    ["BattleRoomResult"] = 0x01D9,
                    ["CheckSinnohPokédex"] = 0x01E8,
                    ["CheckNationalPokédex"] = 0x01E9,
                    ["ShowSinnohCertificate"] = 0x01EA,
                    ["ShowNationalCertificate"] = 0x01EB,
                    ["CheckFossil"] = 0x01F1,
                    ["CheckPokémonLevel"] = 0x01F6,
                    ["WarpLastElevator"] = 0x0204,
                    ["GeoNet"] = 0x0205,
                    ["GreatMarshBinoculars"] = 0x0206,
                    ["PokémonPicture"] = 0x0208,
                    ["HidePicture"] = 0x0209,
                    ["RememberMove"] = 0x0221,
                    ["TeachMove"] = 0x0224,
                    ["CheckTeachMove"] = 0x0225,
                    ["CheckPokémonTrade"] = 0x0228,
                    ["TradeChosenPokémon"] = 0x0229,
                    ["StopTrade"] = 0x022A,
                    ["DecideRules"] = 0x0239,
                    ["HealPokémonAnimation"] = 0x023B,
                    ["ShipAnimation"] = 0x023D,
                    ["PhraseBox1W"] = 0x0243,
                    ["PhraseBox2W"] = 0x0244,
                    ["CheckPhraseBoxInput"] = 0x0249,
                    ["PreparePcAnimation"] = 0x024B,
                    ["OpenPcAnimation"] = 0x024C,
                    ["ClosePcAnimation"] = 0x024D,
                    ["CheckLotteryNumber"] = 0x024E,
                    ["CompareLotteryNumber"] = 0x024F,
                    ["CheckBoxesNumber"] = 0x0252,
                    ["SprtSave"] = 0x0257,
                    ["RetSprtSave"] = 0x0258,
                    ["ElevLgAnimation"] = 0x0259,
                    ["CheckAccessories"] = 0x0261,
                    ["PokéCasino"] = 0x0267,
                    ["UnownMessageBox"] = 0x026D,
                    ["ThankNameInsert"] = 0x0271,
                    ["LeagueCastleView"] = 0x027A,
                    ["PokémonPartyPicture"] = 0x028C,
                    ["CheckFirstTimeChampion"] = 0x028F,
                    ["ShowBattlePointsBox"] = 0x0294,
                    ["HideBattlePointsBox"] = 0x0295,
                    ["ChoiceMulti"] = 0x029D,
                    ["HiddenMachineEffect"] = 0x029E,
                    ["CameraBumpEffect"] = 0x029F,
                    ["DoubleBattle"] = 0x02A0,
                    ["ApplyMovement2"] = 0x02A1,
                    ["ChooseTradePokémon"] = 0x02A5,
                    ["ComparePhraseBoxInput"] = 0x02AA,
                    ["ActivateMysteryGift"] = 0x02AC,
                    ["CheckWildBattle2"] = 0x02BC,
                    ["WildBattle2"] = 0x02BD,
                    ["BikeRide"] = 0x02BF,
                    ["ShowSaveBox"] = 0x02C1,
                    ["HideSaveBox"] = 0x02C2,
                    ["SpinTradeUnion"] = 0x02C6,
                    ["CheckGameVersion"] = 0x02C7,
                    ["FloralClockAnimation"] = 0x02CA,
                    ["PortalEffect"] = 0x0328,
                    ["DisplayFloor"] = 0x0347
                };
                public static Dictionary<string, ushort> movementsDictDPPtHGSS = new Dictionary<string, ushort>() {
                    ["LookUp"] = 0x0000,
                    ["LookDown"] = 0x0001,
                    ["LookLeft"] = 0x0002,
                    ["LookRight"] = 0x0003,
                    ["WalkUpSlow"] = 0x0004,
                    ["WalkDownSlow"] = 0x0005,
                    ["WalkLeftSlow"] = 0x0006,
                    ["WalkRightSlow"] = 0x0007,
                    ["WalkUp"] = 0x0008,
                    ["WalkDown"] = 0x0009,
                    ["WalkLeft"] = 0x000A,
                    ["WalkRight"] = 0x000B,
                    ["WalkUpFast"] = 0x000C,
                    ["WalkDownFast"] = 0x000D,
                    ["WalkLeftFast"] = 0x000E,
                    ["WalkRightFast"] = 0x000F,
                    ["WalkUpVeryFast"] = 0x0010,
                    ["WalkDownVeryFast"] = 0x0011,
                    ["WalkLeftVeryFast"] = 0x0012,
                    ["WalkRightVeryFast"] = 0x0013,
                    ["RunUp"] = 0x0014,
                    ["RunDown"] = 0x0015,
                    ["RunLeft"] = 0x0016,
                    ["RunRight"] = 0x0017,
                    ["WalkUpSlowSite"] = 0x0018,
                    ["WalkDownSlowSite"] = 0x0019,
                    ["WalkLeftSlowSite"] = 0x001A,
                    ["WalkRightSlowSite"] = 0x001B,
                    ["WalkUpSite"] = 0x001C,
                    ["WalkDownSite"] = 0x001D,
                    ["WalkLeftSite"] = 0x001E,
                    ["WalkRightSite"] = 0x001F,
                    ["WalkUpFastSite"] = 0x0020,
                    ["WalkDownFastSite"] = 0x0021,
                    ["WalkLeftFastSite"] = 0x0022,
                    ["WalkRightFastSite"] = 0x0023,
                    ["WalkUpVeryFastSite"] = 0x0024,
                    ["WalkDownVeryFastSite"] = 0x0025,
                    ["WalkLeftVeryFastSite"] = 0x0026,
                    ["WalkRightVeryFastSite"] = 0x0027,
                    ["RunUpSite"] = 0x0028,
                    ["RunDownSite"] = 0x0029,
                    ["RunLeftSite"] = 0x002A,
                    ["RunRightSite"] = 0x002B,
                    ["JumpUpSlow"] = 0x002C,
                    ["JumpDownSlow"] = 0x002D,
                    ["JumpLeftSlow"] = 0x002E,
                    ["JumpRightSlow"] = 0x002F,
                    ["JumpUpSite"] = 0x0030,
                    ["JumpDownSite"] = 0x0031,
                    ["JumpLeftSite"] = 0x0032,
                    ["JumpRightSite"] = 0x0033,
                    ["JumpUp"] = 0x0034,
                    ["JumpDown"] = 0x0035,
                    ["JumpLeft"] = 0x0036,
                    ["JumpRight"] = 0x0037,
                    ["JumpUp2"] = 0x0038,
                    ["JumpDown2"] = 0x0039,
                    ["JumpLeft2"] = 0x003A,
                    ["JumpRight2"] = 0x003B,
                    ["DelayShort"] = 0x003F,
                    ["Delay"] = 0x0042,
                    ["WaitDisappear"] = 0x0045,
                    ["LockDirection"] = 0x0047,
                    ["ReleaseDirection"] = 0x0048,
                    ["Exclamation"] = 0x004B,
                    ["WaitWalkUpSlow"] = 0x004C,
                    ["WaitWalkDownSlow"] = 0x004D,
                    ["WaitWalkLeftSlow"] = 0x004E,
                    ["WaitWalkRightSlow"] = 0x004F,
                    ["WaitWalkUp"] = 0x0050,
                    ["WaitWalkDown"] = 0x0051,
                    ["WaitWalkLeft"] = 0x0052,
                    ["WaitWalkRight"] = 0x0053,
                    ["WaitMoveUp"] = 0x0054,
                    ["WaitMoveDown"] = 0x0055,
                    ["WaitMoveLeft"] = 0x0056,
                    ["WaitMoveRight"] = 0x0057,
                    ["WaitWalkBackUp"] = 0x0058,
                    ["WaitWalkBackDown"] = 0x0059,
                    ["WaitWalkBackLeft"] = 0x005A,
                    ["WaitWalkBackRight"] = 0x005B,
                    ["WaitJumpLeft1"] = 0x005C,
                    ["WaitJumpRight1"] = 0x005D,
                    ["WaitJumpLeft2"] = 0x005E,
                    ["WaitJumpRight2"] = 0x005F,
                    ["WaitMoveSite"] = 0x0064,
                    ["WaitJumpSite"] = 0x0065,
                    ["WaitDoubleExclamation"] = 0x0067,
                    ["WaitMoveForever"] = 0x0068,
                    ["End"] = 0x00FE
                };
            }
            public static Dictionary<string, int> headerOffsetsDict = new Dictionary<string, int>() {
                ["ADAE"] = 0xEEDBC,
                ["APAE"] = 0xEEDBC,

                ["ADAS"] = 0xEEE08,
                ["APAS"] = 0xEEE08,

                ["ADAI"] = 0xEED70,
                ["APAI"] = 0xEED70,

                ["ADAF"] = 0xEEDFC,
                ["APAF"] = 0xEEDFC,

                ["ADAD"] = 0xEEDCC,
                ["APAD"] = 0xEEDCC,

                ["ADAJ"] = 0xF0C28,
                ["APAJ"] = 0xF0C28,

                ["CPUE"] = 0xE601C,
                ["CPUS"] = 0xE60B0,
                ["CPUI"] = 0xE6038,
                ["CPUF"] = 0xE60A4,
                ["CPUD"] = 0xE6074,
                ["CPUJ"] = 0xE56F0,

                ["IPKE"] = 0xF6BE0,
                ["IPGE"] = 0xF6BE0,

                ["IPKS"] = 0xF6BC8,
                ["IPGS"] = 0xF6BD0,

                ["IPKI"] = 0xF6B58,
                ["IPGI"] = 0xF6B58,

                ["IPKF"] = 0xF6BC4,
                ["IPGF"] = 0xF6BC4,

                ["IPKD"] = 0xF6B94,
                ["IPGD"] = 0xF6B94,

                ["IPKJ"] = 0xF6390,
                ["IPGJ"] = 0xF6390
            };
            public static Dictionary<string, string> versionsDict = new Dictionary<string, string>() {
                ["ADAE"] = "D",
                ["ADAS"] = "D",
                ["ADAI"] = "D",
                ["ADAF"] = "D",
                ["ADAD"] = "D",
                ["ADAJ"] = "D",

                ["APAE"] = "P",
                ["APAS"] = "P",
                ["APAI"] = "P",
                ["APAF"] = "P",
                ["APAD"] = "P",
                ["APAJ"] = "P",

                ["CPUE"] = "Plat",
                ["CPUS"] = "Plat",
                ["CPUI"] = "Plat",
                ["CPUF"] = "Plat",
                ["CPUD"] = "Plat",
                ["CPUJ"] = "Plat",
                ["CPUP"] = "Plat",

                ["IPKE"] = "HG",
                ["IPKS"] = "HG",
                ["IPKI"] = "HG",
                ["IPKF"] = "HG",
                ["IPKD"] = "HG",
                ["IPKJ"] = "HG",

                ["IPGE"] = "SS",
                ["IPGS"] = "SS",
                ["IPGI"] = "SS",
                ["IPGF"] = "SS",
                ["IPGD"] = "SS",
                ["IPGJ"] = "SS"
            };

            public static class MatrixCellColors {
                /* Initialize dictionary of colors corresponding to border maps in the matrix editor */
                public static Dictionary<List<uint>, Tuple<Color, Color>> DPPtmatrixColorsDict = new Dictionary<List<uint>, Tuple<Color, Color>> {
                    [new List<uint> { 173, 176, 177, 179 }] = Tuple.Create(Color.ForestGreen, Color.White),
                    [new List<uint> { 174 }] = Tuple.Create(Color.SteelBlue, Color.White),
                    [new List<uint> { 175 }] = Tuple.Create(Color.Sienna, Color.White),
                    [new List<uint> { 178 }] = Tuple.Create(Color.PowderBlue, Color.Black),
                    [new List<uint> { Matrix.EMPTY }] = Tuple.Create(Color.Black, Color.White)
                };
                public static Dictionary<List<uint>, Tuple<Color, Color>> HGSSmatrixColorsDict = new Dictionary<List<uint>, Tuple<Color, Color>> {
                    [new List<uint> { 208 }] = Tuple.Create(Color.ForestGreen, Color.White),
                    [new List<uint> { 209 }] = Tuple.Create(Color.SteelBlue, Color.White),
                    [new List<uint> { 210 }] = Tuple.Create(Color.Sienna, Color.White),
                    [new List<uint> { Matrix.EMPTY }] = Tuple.Create(Color.Black, Color.White)
                };
                public static Dictionary<List<uint>, Tuple<Color, Color>> GenericMatrixColorsDict = new Dictionary<List<uint>, Tuple<Color, Color>> {
                    [new List<uint> { 203 }] = Tuple.Create(Color.FromArgb(80, 200, 16), Color.White),
                    [new List<uint> { 204, 209 }] = Tuple.Create(Color.SteelBlue, Color.White),
                    [new List<uint> { 205, 206 }] = Tuple.Create(Color.DarkGreen, Color.White),
                    [new List<uint> { 207, 208 }] = Tuple.Create(Color.ForestGreen, Color.White),
                    [new List<uint> { 210 }] = Tuple.Create(Color.Sienna, Color.White),
                    [new List<uint> { Matrix.EMPTY }] = Tuple.Create(Color.Black, Color.White)
                };
            }
            public static class AreaPics {
                public static Dictionary<int, string> hgssAreaPicDict = new Dictionary<int, string>() {
                    [0] = "hgsswood",
                    [1] = "hgssgray",
                    [2] = "hgsswall",
                    [3] = "empty",
                    [4] = "hgsstown",
                    [5] = "hgsscave",
                    [6] = "hgssfield",
                    [7] = "hgsslake",
                    [8] = "hgssforest",
                    [9] = "hgsswater",
                };
            }
            public static class WeatherPics {
                public static Dictionary<int, string> dpWeatherImageDict = new Dictionary<int, string>() {
                    [0] = "dpnormal",
                    [1] = "dpcloudy",
                    [2] = "dprain",
                    [3] = "dpheavyrain",
                    [4] = "dpthunderstorm",
                    [5] = "dpsnowslow",
                    [6] = "dpdiamondsnow",
                    [7] = "dpblizzard",
                    [8] = "dpsandfall",
                    [9] = "dpsandstorm",
                    [10] = "dphail",
                    [11] = "dprocksascending",
                    [12] = "dpfog",
                    [13] = "dpfog",
                    [14] = "dpdark",
                    [15] = "dplightning",
                    [16] = "dplightsandstorm"
                };
                public static Dictionary<int, string> ptWeatherImageDict = new Dictionary<int, string>() {
                    [0] = "ptnormal",
                    [1] = "ptcloudy",
                    [2] = "ptrain",
                    [3] = "ptheavyrain",
                    [4] = "ptthunderstorm",
                    [5] = "ptsnowslow",
                    [6] = "ptDsnow",
                    [7] = "ptblizzard",
                    [8] = "ptsandfall",
                    [9] = "ptsandstorm",
                    [10] = "pthail",
                    [11] = "ptrocksascending",
                    [12] = "ptfog",
                    [13] = "ptfog",
                    [14] = "ptdark",
                    [15] = "ptlightning",
                    [16] = "ptlightsandstorm",
                    [17] = "ptforestweather",
                    [18] = "ptspotlight",
                    [19] = "ptspotlight"
                };
                public static Dictionary<List<int>, string> hgssweatherImageDict = new Dictionary<List<int>, string>() {
                    [new List<int> { 0, 1 }] = "hgssnormal",
                    [new List<int> { 2, 3, 4, 5, 6, 7, 8 }] = "hgssrain",
                    [new List<int> { 9, 10, 11, 12, 13, 15 }] = "hgsssnow",
                    [new List<int> { 14 }] = "hgssnormal", //sandstorm in battle only
                    [new List<int> { 16, 17 }] = "hgssdiamond",
                    [new List<int> { 18, 19, 20, 21 }] = "hgssfog",
                    [new List<int> { 22, 23 }] = "hgssdark",
                    [new List<int> { 24, 25 }] = "hgssdark2",
                    [new List<int> { 26 }] = "hgssArcade"
                };
            }
        }
    }
}
