//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovementNamesW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovementNamesW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.MovementNamesW", typeof(MovementNamesW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00FE.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004B.
        /// </summary>
        internal static string Exclamation {
            get {
                return ResourceManager.GetString("Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0031.
        /// </summary>
        internal static string JumpDown {
            get {
                return ResourceManager.GetString("JumpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0035.
        /// </summary>
        internal static string JumpDown1 {
            get {
                return ResourceManager.GetString("JumpDown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0039.
        /// </summary>
        internal static string JumpDown2 {
            get {
                return ResourceManager.GetString("JumpDown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002D.
        /// </summary>
        internal static string JumpDownSlow {
            get {
                return ResourceManager.GetString("JumpDownSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0032.
        /// </summary>
        internal static string JumpLeft {
            get {
                return ResourceManager.GetString("JumpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0036.
        /// </summary>
        internal static string JumpLeft1 {
            get {
                return ResourceManager.GetString("JumpLeft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003A.
        /// </summary>
        internal static string JumpLeft2 {
            get {
                return ResourceManager.GetString("JumpLeft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002E.
        /// </summary>
        internal static string JumpLeftSlow {
            get {
                return ResourceManager.GetString("JumpLeftSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0033.
        /// </summary>
        internal static string JumpRight {
            get {
                return ResourceManager.GetString("JumpRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0037.
        /// </summary>
        internal static string JumpRight1 {
            get {
                return ResourceManager.GetString("JumpRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003B.
        /// </summary>
        internal static string JumpRight2 {
            get {
                return ResourceManager.GetString("JumpRight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002F.
        /// </summary>
        internal static string JumpRightSlow {
            get {
                return ResourceManager.GetString("JumpRightSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0030.
        /// </summary>
        internal static string JumpUp {
            get {
                return ResourceManager.GetString("JumpUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0034.
        /// </summary>
        internal static string JumpUp1 {
            get {
                return ResourceManager.GetString("JumpUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0038.
        /// </summary>
        internal static string JumpUp2 {
            get {
                return ResourceManager.GetString("JumpUp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002C.
        /// </summary>
        internal static string JumpUpSlow {
            get {
                return ResourceManager.GetString("JumpUpSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0015.
        /// </summary>
        internal static string RunDown {
            get {
                return ResourceManager.GetString("RunDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0029.
        /// </summary>
        internal static string RunDownSite {
            get {
                return ResourceManager.GetString("RunDownSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0016.
        /// </summary>
        internal static string RunLeft {
            get {
                return ResourceManager.GetString("RunLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002A.
        /// </summary>
        internal static string RunLeftSite {
            get {
                return ResourceManager.GetString("RunLeftSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0017.
        /// </summary>
        internal static string RunRight {
            get {
                return ResourceManager.GetString("RunRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002B.
        /// </summary>
        internal static string RunRightSite {
            get {
                return ResourceManager.GetString("RunRightSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0014.
        /// </summary>
        internal static string RunUp {
            get {
                return ResourceManager.GetString("RunUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0028.
        /// </summary>
        internal static string RunUpSite {
            get {
                return ResourceManager.GetString("RunUpSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        internal static string SeeDown {
            get {
                return ResourceManager.GetString("SeeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        internal static string SeeLeft {
            get {
                return ResourceManager.GetString("SeeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        internal static string SeeRight {
            get {
                return ResourceManager.GetString("SeeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string SeeUp {
            get {
                return ResourceManager.GetString("SeeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0045.
        /// </summary>
        internal static string WaitDisappear {
            get {
                return ResourceManager.GetString("WaitDisappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0067.
        /// </summary>
        internal static string WaitDoubleExclamation {
            get {
                return ResourceManager.GetString("WaitDoubleExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005C.
        /// </summary>
        internal static string WaitJumpLeft1 {
            get {
                return ResourceManager.GetString("WaitJumpLeft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005E.
        /// </summary>
        internal static string WaitJumpLeft2 {
            get {
                return ResourceManager.GetString("WaitJumpLeft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005D.
        /// </summary>
        internal static string WaitJumpRight1 {
            get {
                return ResourceManager.GetString("WaitJumpRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005F.
        /// </summary>
        internal static string WaitJumpRight2 {
            get {
                return ResourceManager.GetString("WaitJumpRight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0065.
        /// </summary>
        internal static string WaitJumpSite {
            get {
                return ResourceManager.GetString("WaitJumpSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0055.
        /// </summary>
        internal static string WaitMoveDown {
            get {
                return ResourceManager.GetString("WaitMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0068.
        /// </summary>
        internal static string WaitMoveForever {
            get {
                return ResourceManager.GetString("WaitMoveForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0056.
        /// </summary>
        internal static string WaitMoveLeft {
            get {
                return ResourceManager.GetString("WaitMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0057.
        /// </summary>
        internal static string WaitMoveRight {
            get {
                return ResourceManager.GetString("WaitMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0064.
        /// </summary>
        internal static string WaitMoveSite {
            get {
                return ResourceManager.GetString("WaitMoveSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0054.
        /// </summary>
        internal static string WaitMoveUp {
            get {
                return ResourceManager.GetString("WaitMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0059.
        /// </summary>
        internal static string WaitWalkBackDown {
            get {
                return ResourceManager.GetString("WaitWalkBackDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005A.
        /// </summary>
        internal static string WaitWalkBackLeft {
            get {
                return ResourceManager.GetString("WaitWalkBackLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005B.
        /// </summary>
        internal static string WaitWalkBackRight {
            get {
                return ResourceManager.GetString("WaitWalkBackRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0058.
        /// </summary>
        internal static string WaitWalkBackUp {
            get {
                return ResourceManager.GetString("WaitWalkBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051.
        /// </summary>
        internal static string WaitWalkDown {
            get {
                return ResourceManager.GetString("WaitWalkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004D.
        /// </summary>
        internal static string WaitWalkDownSlow {
            get {
                return ResourceManager.GetString("WaitWalkDownSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0052.
        /// </summary>
        internal static string WaitWalkLeft {
            get {
                return ResourceManager.GetString("WaitWalkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004E.
        /// </summary>
        internal static string WaitWalkLeftSlow {
            get {
                return ResourceManager.GetString("WaitWalkLeftSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0053.
        /// </summary>
        internal static string WaitWalkRight {
            get {
                return ResourceManager.GetString("WaitWalkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004F.
        /// </summary>
        internal static string WaitWalkRightSlow {
            get {
                return ResourceManager.GetString("WaitWalkRightSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0050.
        /// </summary>
        internal static string WaitWalkUp {
            get {
                return ResourceManager.GetString("WaitWalkUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004C.
        /// </summary>
        internal static string WaitWalkUpSlow {
            get {
                return ResourceManager.GetString("WaitWalkUpSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0009.
        /// </summary>
        internal static string WalkDown {
            get {
                return ResourceManager.GetString("WalkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000D.
        /// </summary>
        internal static string WalkDownFast {
            get {
                return ResourceManager.GetString("WalkDownFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0021.
        /// </summary>
        internal static string WalkDownFastSite {
            get {
                return ResourceManager.GetString("WalkDownFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001D.
        /// </summary>
        internal static string WalkDownSite {
            get {
                return ResourceManager.GetString("WalkDownSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005.
        /// </summary>
        internal static string WalkDownSlow {
            get {
                return ResourceManager.GetString("WalkDownSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0019.
        /// </summary>
        internal static string WalkDownSlowSite {
            get {
                return ResourceManager.GetString("WalkDownSlowSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0011.
        /// </summary>
        internal static string WalkDownVeryFast {
            get {
                return ResourceManager.GetString("WalkDownVeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0025.
        /// </summary>
        internal static string WalkDownVeryFastSite {
            get {
                return ResourceManager.GetString("WalkDownVeryFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000A.
        /// </summary>
        internal static string WalkLeft {
            get {
                return ResourceManager.GetString("WalkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000E.
        /// </summary>
        internal static string WalkLeftFast {
            get {
                return ResourceManager.GetString("WalkLeftFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0022.
        /// </summary>
        internal static string WalkLeftFastSite {
            get {
                return ResourceManager.GetString("WalkLeftFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001E.
        /// </summary>
        internal static string WalkLeftSite {
            get {
                return ResourceManager.GetString("WalkLeftSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0006.
        /// </summary>
        internal static string WalkLeftSlow {
            get {
                return ResourceManager.GetString("WalkLeftSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001A.
        /// </summary>
        internal static string WalkLeftSlowSite {
            get {
                return ResourceManager.GetString("WalkLeftSlowSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0012.
        /// </summary>
        internal static string WalkLeftVeryFast {
            get {
                return ResourceManager.GetString("WalkLeftVeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0026.
        /// </summary>
        internal static string WalkLeftVeryFastSite {
            get {
                return ResourceManager.GetString("WalkLeftVeryFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000B.
        /// </summary>
        internal static string WalkRight {
            get {
                return ResourceManager.GetString("WalkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000F.
        /// </summary>
        internal static string WalkRightFast {
            get {
                return ResourceManager.GetString("WalkRightFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0023.
        /// </summary>
        internal static string WalkRightFastSite {
            get {
                return ResourceManager.GetString("WalkRightFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001F.
        /// </summary>
        internal static string WalkRightSite {
            get {
                return ResourceManager.GetString("WalkRightSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0007.
        /// </summary>
        internal static string WalkRightSlow {
            get {
                return ResourceManager.GetString("WalkRightSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001B.
        /// </summary>
        internal static string WalkRightSlowSite {
            get {
                return ResourceManager.GetString("WalkRightSlowSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0013.
        /// </summary>
        internal static string WalkRightVeryFast {
            get {
                return ResourceManager.GetString("WalkRightVeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0027.
        /// </summary>
        internal static string WalkRightVeryFastSite {
            get {
                return ResourceManager.GetString("WalkRightVeryFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0008.
        /// </summary>
        internal static string WalkUp {
            get {
                return ResourceManager.GetString("WalkUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000C.
        /// </summary>
        internal static string WalkUpFast {
            get {
                return ResourceManager.GetString("WalkUpFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0020.
        /// </summary>
        internal static string WalkUpFastSite {
            get {
                return ResourceManager.GetString("WalkUpFastSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001C.
        /// </summary>
        internal static string WalkUpSite {
            get {
                return ResourceManager.GetString("WalkUpSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004.
        /// </summary>
        internal static string WalkUpSlow {
            get {
                return ResourceManager.GetString("WalkUpSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0018.
        /// </summary>
        internal static string WalkUpSlowSite {
            get {
                return ResourceManager.GetString("WalkUpSlowSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010.
        /// </summary>
        internal static string WalkUpVeryFast {
            get {
                return ResourceManager.GetString("WalkUpVeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0024.
        /// </summary>
        internal static string WalkUpVeryFastSite {
            get {
                return ResourceManager.GetString("WalkUpVeryFastSite", resourceCulture);
            }
        }
    }
}
