//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPRE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovementNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovementNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.MovementNames", typeof(MovementNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeeUp.
        /// </summary>
        internal static string _0000 {
            get {
                return ResourceManager.GetString("0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeeDown.
        /// </summary>
        internal static string _0001 {
            get {
                return ResourceManager.GetString("0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeeLeft.
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeeRight.
        /// </summary>
        internal static string _0003 {
            get {
                return ResourceManager.GetString("0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpSlow.
        /// </summary>
        internal static string _0004 {
            get {
                return ResourceManager.GetString("0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownSlow.
        /// </summary>
        internal static string _0005 {
            get {
                return ResourceManager.GetString("0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftSlow.
        /// </summary>
        internal static string _0006 {
            get {
                return ResourceManager.GetString("0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightSlow.
        /// </summary>
        internal static string _0007 {
            get {
                return ResourceManager.GetString("0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUp.
        /// </summary>
        internal static string _0008 {
            get {
                return ResourceManager.GetString("0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDown.
        /// </summary>
        internal static string _0009 {
            get {
                return ResourceManager.GetString("0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeft.
        /// </summary>
        internal static string _000A {
            get {
                return ResourceManager.GetString("000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRight.
        /// </summary>
        internal static string _000B {
            get {
                return ResourceManager.GetString("000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpFast.
        /// </summary>
        internal static string _000C {
            get {
                return ResourceManager.GetString("000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownFast.
        /// </summary>
        internal static string _000D {
            get {
                return ResourceManager.GetString("000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftFast.
        /// </summary>
        internal static string _000E {
            get {
                return ResourceManager.GetString("000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightFast.
        /// </summary>
        internal static string _000F {
            get {
                return ResourceManager.GetString("000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpVeryFast.
        /// </summary>
        internal static string _0010 {
            get {
                return ResourceManager.GetString("0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownVeryFast.
        /// </summary>
        internal static string _0011 {
            get {
                return ResourceManager.GetString("0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftVeryFast.
        /// </summary>
        internal static string _0012 {
            get {
                return ResourceManager.GetString("0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightVeryFast.
        /// </summary>
        internal static string _0013 {
            get {
                return ResourceManager.GetString("0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunUp.
        /// </summary>
        internal static string _0014 {
            get {
                return ResourceManager.GetString("0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunDown.
        /// </summary>
        internal static string _0015 {
            get {
                return ResourceManager.GetString("0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunLeft.
        /// </summary>
        internal static string _0016 {
            get {
                return ResourceManager.GetString("0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunRight.
        /// </summary>
        internal static string _0017 {
            get {
                return ResourceManager.GetString("0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpSlowSite.
        /// </summary>
        internal static string _0018 {
            get {
                return ResourceManager.GetString("0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownSlowSite.
        /// </summary>
        internal static string _0019 {
            get {
                return ResourceManager.GetString("0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftSlowSite.
        /// </summary>
        internal static string _001A {
            get {
                return ResourceManager.GetString("001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightSlowSite.
        /// </summary>
        internal static string _001B {
            get {
                return ResourceManager.GetString("001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpSite.
        /// </summary>
        internal static string _001C {
            get {
                return ResourceManager.GetString("001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownSite.
        /// </summary>
        internal static string _001D {
            get {
                return ResourceManager.GetString("001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftSite.
        /// </summary>
        internal static string _001E {
            get {
                return ResourceManager.GetString("001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightSite.
        /// </summary>
        internal static string _001F {
            get {
                return ResourceManager.GetString("001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpFastSite.
        /// </summary>
        internal static string _0020 {
            get {
                return ResourceManager.GetString("0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownFastSite.
        /// </summary>
        internal static string _0021 {
            get {
                return ResourceManager.GetString("0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftFastSite.
        /// </summary>
        internal static string _0022 {
            get {
                return ResourceManager.GetString("0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightFastSite.
        /// </summary>
        internal static string _0023 {
            get {
                return ResourceManager.GetString("0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkUpVeryFastSite.
        /// </summary>
        internal static string _0024 {
            get {
                return ResourceManager.GetString("0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkDownVeryFastSite.
        /// </summary>
        internal static string _0025 {
            get {
                return ResourceManager.GetString("0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkLeftVeryFastSite.
        /// </summary>
        internal static string _0026 {
            get {
                return ResourceManager.GetString("0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalkRightVeryFastSite.
        /// </summary>
        internal static string _0027 {
            get {
                return ResourceManager.GetString("0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunUpSite.
        /// </summary>
        internal static string _0028 {
            get {
                return ResourceManager.GetString("0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunDownSite.
        /// </summary>
        internal static string _0029 {
            get {
                return ResourceManager.GetString("0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunLeftSite.
        /// </summary>
        internal static string _002A {
            get {
                return ResourceManager.GetString("002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunRightSite.
        /// </summary>
        internal static string _002B {
            get {
                return ResourceManager.GetString("002B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpUpSlow.
        /// </summary>
        internal static string _002C {
            get {
                return ResourceManager.GetString("002C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpDownSlow.
        /// </summary>
        internal static string _002D {
            get {
                return ResourceManager.GetString("002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpLeftSlow.
        /// </summary>
        internal static string _002E {
            get {
                return ResourceManager.GetString("002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpRightSlow.
        /// </summary>
        internal static string _002F {
            get {
                return ResourceManager.GetString("002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpUp.
        /// </summary>
        internal static string _0030 {
            get {
                return ResourceManager.GetString("0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpDown.
        /// </summary>
        internal static string _0031 {
            get {
                return ResourceManager.GetString("0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpLeft.
        /// </summary>
        internal static string _0032 {
            get {
                return ResourceManager.GetString("0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpRight.
        /// </summary>
        internal static string _0033 {
            get {
                return ResourceManager.GetString("0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpUp1.
        /// </summary>
        internal static string _0034 {
            get {
                return ResourceManager.GetString("0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpDown1.
        /// </summary>
        internal static string _0035 {
            get {
                return ResourceManager.GetString("0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpLeft1.
        /// </summary>
        internal static string _0036 {
            get {
                return ResourceManager.GetString("0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpRight1.
        /// </summary>
        internal static string _0037 {
            get {
                return ResourceManager.GetString("0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpUp2.
        /// </summary>
        internal static string _0038 {
            get {
                return ResourceManager.GetString("0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpDown2.
        /// </summary>
        internal static string _0039 {
            get {
                return ResourceManager.GetString("0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpLeft2.
        /// </summary>
        internal static string _003A {
            get {
                return ResourceManager.GetString("003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpRight2.
        /// </summary>
        internal static string _003B {
            get {
                return ResourceManager.GetString("003B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitDisappear.
        /// </summary>
        internal static string _0045 {
            get {
                return ResourceManager.GetString("0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclamation.
        /// </summary>
        internal static string _004B {
            get {
                return ResourceManager.GetString("004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkUpSlow.
        /// </summary>
        internal static string _004C {
            get {
                return ResourceManager.GetString("004C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkDownSlow.
        /// </summary>
        internal static string _004D {
            get {
                return ResourceManager.GetString("004D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkLeftSlow.
        /// </summary>
        internal static string _004E {
            get {
                return ResourceManager.GetString("004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkRightSlow.
        /// </summary>
        internal static string _004F {
            get {
                return ResourceManager.GetString("004F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkUp.
        /// </summary>
        internal static string _0050 {
            get {
                return ResourceManager.GetString("0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkDown.
        /// </summary>
        internal static string _0051 {
            get {
                return ResourceManager.GetString("0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkLeft.
        /// </summary>
        internal static string _0052 {
            get {
                return ResourceManager.GetString("0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkRight.
        /// </summary>
        internal static string _0053 {
            get {
                return ResourceManager.GetString("0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveUp.
        /// </summary>
        internal static string _0054 {
            get {
                return ResourceManager.GetString("0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveDown.
        /// </summary>
        internal static string _0055 {
            get {
                return ResourceManager.GetString("0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveLeft.
        /// </summary>
        internal static string _0056 {
            get {
                return ResourceManager.GetString("0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveRight.
        /// </summary>
        internal static string _0057 {
            get {
                return ResourceManager.GetString("0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkBackUp.
        /// </summary>
        internal static string _0058 {
            get {
                return ResourceManager.GetString("0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkBackDown.
        /// </summary>
        internal static string _0059 {
            get {
                return ResourceManager.GetString("0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkBackLeft.
        /// </summary>
        internal static string _005A {
            get {
                return ResourceManager.GetString("005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitWalkBackRight.
        /// </summary>
        internal static string _005B {
            get {
                return ResourceManager.GetString("005B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitJumpLeft1.
        /// </summary>
        internal static string _005C {
            get {
                return ResourceManager.GetString("005C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitJumpRight1.
        /// </summary>
        internal static string _005D {
            get {
                return ResourceManager.GetString("005D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitJumpLeft2.
        /// </summary>
        internal static string _005E {
            get {
                return ResourceManager.GetString("005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitJumpRight2.
        /// </summary>
        internal static string _005F {
            get {
                return ResourceManager.GetString("005F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveSite.
        /// </summary>
        internal static string _0064 {
            get {
                return ResourceManager.GetString("0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitJumpSite.
        /// </summary>
        internal static string _0065 {
            get {
                return ResourceManager.GetString("0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitDoubleExclamation.
        /// </summary>
        internal static string _0067 {
            get {
                return ResourceManager.GetString("0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoveForever.
        /// </summary>
        internal static string _0068 {
            get {
                return ResourceManager.GetString("0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000A.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000B.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000C.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000D.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000E.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000F.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0011.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0012.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0013.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0014.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0015.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0016.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0017.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0018.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0019.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001A.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001B.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001C.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001D.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001E.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001F.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0020.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0021.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0022.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0023.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0024.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0025.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0026.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0027.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0028.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0029.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002A.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002B.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002C.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002D.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002E.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002F.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0030.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0031.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0032.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0033.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0034.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0035.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0036.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0037.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0038.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0039.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003A.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003B.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0006.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0045.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004B.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004C.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004D.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004E.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004F.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0050.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051.
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0052.
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0053.
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0007.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0054.
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0055.
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0056.
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0057.
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0058.
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0059.
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005A.
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005B.
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005C.
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005D.
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0008.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005E.
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005F.
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0064.
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0065.
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0067.
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0068.
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0009.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
