//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_Map.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNamesGS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNamesGS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptNamesGS", typeof(ScriptNamesGS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nop.
        /// </summary>
        internal static string _0000 {
            get {
                return ResourceManager.GetString("0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nop1.
        /// </summary>
        internal static string _0001 {
            get {
                return ResourceManager.GetString("0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return2.
        /// </summary>
        internal static string _0003 {
            get {
                return ResourceManager.GetString("0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string _0011 {
            get {
                return ResourceManager.GetString("0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If2.
        /// </summary>
        internal static string _0012 {
            get {
                return ResourceManager.GetString("0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallStandard.
        /// </summary>
        internal static string _0014 {
            get {
                return ResourceManager.GetString("0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string _0016 {
            get {
                return ResourceManager.GetString("0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string _001A {
            get {
                return ResourceManager.GetString("001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string _001B {
            get {
                return ResourceManager.GetString("001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareLastResultJump.
        /// </summary>
        internal static string _001C {
            get {
                return ResourceManager.GetString("001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareLastResultCall.
        /// </summary>
        internal static string _001D {
            get {
                return ResourceManager.GetString("001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFlag.
        /// </summary>
        internal static string _001E {
            get {
                return ResourceManager.GetString("001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearFlag.
        /// </summary>
        internal static string _001F {
            get {
                return ResourceManager.GetString("001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFlag.
        /// </summary>
        internal static string _0020 {
            get {
                return ResourceManager.GetString("0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string _0027 {
            get {
                return ResourceManager.GetString("0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVar.
        /// </summary>
        internal static string _0029 {
            get {
                return ResourceManager.GetString("0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyVar.
        /// </summary>
        internal static string _002A {
            get {
                return ResourceManager.GetString("002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _002D {
            get {
                return ResourceManager.GetString("002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message2.
        /// </summary>
        internal static string _002E {
            get {
                return ResourceManager.GetString("002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitButton.
        /// </summary>
        internal static string _0032 {
            get {
                return ResourceManager.GetString("0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMessageOnKeyPress.
        /// </summary>
        internal static string _0035 {
            get {
                return ResourceManager.GetString("0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreezeMessageBox.
        /// </summary>
        internal static string _0036 {
            get {
                return ResourceManager.GetString("0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallMessageBox.
        /// </summary>
        internal static string _0037 {
            get {
                return ResourceManager.GetString("0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorMessageBox.
        /// </summary>
        internal static string _0038 {
            get {
                return ResourceManager.GetString("0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeMessageBox.
        /// </summary>
        internal static string _0039 {
            get {
                return ResourceManager.GetString("0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoMapMessageBox.
        /// </summary>
        internal static string _003A {
            get {
                return ResourceManager.GetString("003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        internal static string _0040 {
            get {
                return ResourceManager.GetString("0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi2.
        /// </summary>
        internal static string _0041 {
            get {
                return ResourceManager.GetString("0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextScriptMulti.
        /// </summary>
        internal static string _0042 {
            get {
                return ResourceManager.GetString("0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMulti.
        /// </summary>
        internal static string _0043 {
            get {
                return ResourceManager.GetString("0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi3.
        /// </summary>
        internal static string _0044 {
            get {
                return ResourceManager.GetString("0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiRow.
        /// </summary>
        internal static string _0048 {
            get {
                return ResourceManager.GetString("0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayFanfare.
        /// </summary>
        internal static string _0049 {
            get {
                return ResourceManager.GetString("0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayFanfare2.
        /// </summary>
        internal static string _004A {
            get {
                return ResourceManager.GetString("004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitFanfare.
        /// </summary>
        internal static string _004B {
            get {
                return ResourceManager.GetString("004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayCry.
        /// </summary>
        internal static string _004C {
            get {
                return ResourceManager.GetString("004C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitCry.
        /// </summary>
        internal static string _004D {
            get {
                return ResourceManager.GetString("004D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaySound.
        /// </summary>
        internal static string _004E {
            get {
                return ResourceManager.GetString("004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FadeDefaultMusic.
        /// </summary>
        internal static string _004F {
            get {
                return ResourceManager.GetString("004F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayMusic.
        /// </summary>
        internal static string _0050 {
            get {
                return ResourceManager.GetString("0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopMusic.
        /// </summary>
        internal static string _0051 {
            get {
                return ResourceManager.GetString("0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartMusic.
        /// </summary>
        internal static string _0052 {
            get {
                return ResourceManager.GetString("0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchMusic.
        /// </summary>
        internal static string _0054 {
            get {
                return ResourceManager.GetString("0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchMusic2.
        /// </summary>
        internal static string _005A {
            get {
                return ResourceManager.GetString("005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyMovement.
        /// </summary>
        internal static string _005E {
            get {
                return ResourceManager.GetString("005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMovement.
        /// </summary>
        internal static string _005F {
            get {
                return ResourceManager.GetString("005F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockAll.
        /// </summary>
        internal static string _0060 {
            get {
                return ResourceManager.GetString("0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseAll.
        /// </summary>
        internal static string _0061 {
            get {
                return ResourceManager.GetString("0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string _0062 {
            get {
                return ResourceManager.GetString("0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string _0063 {
            get {
                return ResourceManager.GetString("0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPeople.
        /// </summary>
        internal static string _0064 {
            get {
                return ResourceManager.GetString("0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemovePeople.
        /// </summary>
        internal static string _0065 {
            get {
                return ResourceManager.GetString("0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockCam.
        /// </summary>
        internal static string _0066 {
            get {
                return ResourceManager.GetString("0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacePlayer.
        /// </summary>
        internal static string _0068 {
            get {
                return ResourceManager.GetString("0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSpritePosition.
        /// </summary>
        internal static string _0069 {
            get {
                return ResourceManager.GetString("0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPersonPosition.
        /// </summary>
        internal static string _006B {
            get {
                return ResourceManager.GetString("006B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueFollow.
        /// </summary>
        internal static string _006C {
            get {
                return ResourceManager.GetString("006C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FollowHero.
        /// </summary>
        internal static string _006D {
            get {
                return ResourceManager.GetString("006D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveMoney.
        /// </summary>
        internal static string _006E {
            get {
                return ResourceManager.GetString("006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeMoney.
        /// </summary>
        internal static string _006F {
            get {
                return ResourceManager.GetString("006F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMoney.
        /// </summary>
        internal static string _0070 {
            get {
                return ResourceManager.GetString("0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMoney.
        /// </summary>
        internal static string _0071 {
            get {
                return ResourceManager.GetString("0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideMoney.
        /// </summary>
        internal static string _0072 {
            get {
                return ResourceManager.GetString("0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeItem.
        /// </summary>
        internal static string _007E {
            get {
                return ResourceManager.GetString("007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveItem.
        /// </summary>
        internal static string _007F {
            get {
                return ResourceManager.GetString("007F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckItem.
        /// </summary>
        internal static string _0080 {
            get {
                return ResourceManager.GetString("0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMessage.
        /// </summary>
        internal static string _0084 {
            get {
                return ResourceManager.GetString("0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveStoredPokemon.
        /// </summary>
        internal static string _0089 {
            get {
                return ResourceManager.GetString("0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordPokegearNumber.
        /// </summary>
        internal static string _0092 {
            get {
                return ResourceManager.GetString("0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallEnd.
        /// </summary>
        internal static string _0096 {
            get {
                return ResourceManager.GetString("0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi.
        /// </summary>
        internal static string _0098 {
            get {
                return ResourceManager.GetString("0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenPokemonDress.
        /// </summary>
        internal static string _009A {
            get {
                return ResourceManager.GetString("009A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenPokegearMap.
        /// </summary>
        internal static string _009D {
            get {
                return ResourceManager.GetString("009D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallEnd2.
        /// </summary>
        internal static string _00A1 {
            get {
                return ResourceManager.GetString("00A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndGame.
        /// </summary>
        internal static string _00A3 {
            get {
                return ResourceManager.GetString("00A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC.
        /// </summary>
        internal static string _00A6 {
            get {
                return ResourceManager.GetString("00A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivePokemonNickname.
        /// </summary>
        internal static string _00AD {
            get {
                return ResourceManager.GetString("00AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FadeScreen.
        /// </summary>
        internal static string _00AE {
            get {
                return ResourceManager.GetString("00AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetScreen.
        /// </summary>
        internal static string _00AF {
            get {
                return ResourceManager.GetString("00AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        internal static string _00B0 {
            get {
                return ResourceManager.GetString("00B0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HallFameData.
        /// </summary>
        internal static string _00B1 {
            get {
                return ResourceManager.GetString("00B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC1.
        /// </summary>
        internal static string _00B3 {
            get {
                return ResourceManager.GetString("00B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableHero.
        /// </summary>
        internal static string _00BE {
            get {
                return ResourceManager.GetString("00BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableRival.
        /// </summary>
        internal static string _00BF {
            get {
                return ResourceManager.GetString("00BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAlter.
        /// </summary>
        internal static string _00C0 {
            get {
                return ResourceManager.GetString("00C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariablePokemon.
        /// </summary>
        internal static string _00C1 {
            get {
                return ResourceManager.GetString("00C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableItem.
        /// </summary>
        internal static string _00C2 {
            get {
                return ResourceManager.GetString("00C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAttackItem.
        /// </summary>
        internal static string _00C4 {
            get {
                return ResourceManager.GetString("00C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAttack.
        /// </summary>
        internal static string _00C5 {
            get {
                return ResourceManager.GetString("00C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableNumber.
        /// </summary>
        internal static string _00C6 {
            get {
                return ResourceManager.GetString("00C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariablePokemonNickname.
        /// </summary>
        internal static string _00C7 {
            get {
                return ResourceManager.GetString("00C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableObject.
        /// </summary>
        internal static string _00C8 {
            get {
                return ResourceManager.GetString("00C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariablePokemonStored.
        /// </summary>
        internal static string _00CA {
            get {
                return ResourceManager.GetString("00CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckStarter.
        /// </summary>
        internal static string _00CD {
            get {
                return ResourceManager.GetString("00CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainerBattle.
        /// </summary>
        internal static string _00D5 {
            get {
                return ResourceManager.GetString("00D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LostGoPokecenter.
        /// </summary>
        internal static string _00DB {
            get {
                return ResourceManager.GetString("00DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckLost.
        /// </summary>
        internal static string _00DC {
            get {
                return ResourceManager.GetString("00DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreStarter.
        /// </summary>
        internal static string _00DE {
            get {
                return ResourceManager.GetString("00DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChecPokemonGender.
        /// </summary>
        internal static string _00EF {
            get {
                return ResourceManager.GetString("00EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarpLift.
        /// </summary>
        internal static string _00F0 {
            get {
                return ResourceManager.GetString("00F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFloor.
        /// </summary>
        internal static string _00F1 {
            get {
                return ResourceManager.GetString("00F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WirelessBattleWait.
        /// </summary>
        internal static string _00F3 {
            get {
                return ResourceManager.GetString("00F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonContest.
        /// </summary>
        internal static string _00F7 {
            get {
                return ResourceManager.GetString("00F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckGender.
        /// </summary>
        internal static string _0119 {
            get {
                return ResourceManager.GetString("0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealPokemon.
        /// </summary>
        internal static string _011A {
            get {
                return ResourceManager.GetString("011A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivatePokedex.
        /// </summary>
        internal static string _0123 {
            get {
                return ResourceManager.GetString("0123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveRunningShoes.
        /// </summary>
        internal static string _0125 {
            get {
                return ResourceManager.GetString("0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBadge.
        /// </summary>
        internal static string _0126 {
            get {
                return ResourceManager.GetString("0126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableBadge.
        /// </summary>
        internal static string _0127 {
            get {
                return ResourceManager.GetString("0127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableBadge.
        /// </summary>
        internal static string _0128 {
            get {
                return ResourceManager.GetString("0128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrepareDoorAnimation.
        /// </summary>
        internal static string _0133 {
            get {
                return ResourceManager.GetString("0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDoor.
        /// </summary>
        internal static string _0134 {
            get {
                return ResourceManager.GetString("0134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveDoor.
        /// </summary>
        internal static string _0135 {
            get {
                return ResourceManager.GetString("0135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenDoor.
        /// </summary>
        internal static string _0136 {
            get {
                return ResourceManager.GetString("0136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitDoor.
        /// </summary>
        internal static string _0137 {
            get {
                return ResourceManager.GetString("0137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VermillionGymAnimation.
        /// </summary>
        internal static string _0141 {
            get {
                return ResourceManager.GetString("0141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VermillionGymBin.
        /// </summary>
        internal static string _0142 {
            get {
                return ResourceManager.GetString("0142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzaleaGym.
        /// </summary>
        internal static string _0147 {
            get {
                return ResourceManager.GetString("0147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzaleaGym2.
        /// </summary>
        internal static string _0148 {
            get {
                return ResourceManager.GetString("0148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPartyNumber.
        /// </summary>
        internal static string _014C {
            get {
                return ResourceManager.GetString("014C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOverworldPosition.
        /// </summary>
        internal static string _0153 {
            get {
                return ResourceManager.GetString("0153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonMenu.
        /// </summary>
        internal static string _015D {
            get {
                return ResourceManager.GetString("015D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonMenu2.
        /// </summary>
        internal static string _015E {
            get {
                return ResourceManager.GetString("015E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePokemonMenu.
        /// </summary>
        internal static string _015F {
            get {
                return ResourceManager.GetString("015F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePokemonNumber.
        /// </summary>
        internal static string _0162 {
            get {
                return ResourceManager.GetString("0162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIfPokemonTraded.
        /// </summary>
        internal static string _0163 {
            get {
                return ResourceManager.GetString("0163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckHiroMoneyNumber.
        /// </summary>
        internal static string _0170 {
            get {
                return ResourceManager.GetString("0170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenMail.
        /// </summary>
        internal static string _0178 {
            get {
                return ResourceManager.GetString("0178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMail.
        /// </summary>
        internal static string _0179 {
            get {
                return ResourceManager.GetString("0179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparePokemonHeight.
        /// </summary>
        internal static string _0188 {
            get {
                return ResourceManager.GetString("0188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonHeight.
        /// </summary>
        internal static string _0189 {
            get {
                return ResourceManager.GetString("0189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonDelete.
        /// </summary>
        internal static string _018A {
            get {
                return ResourceManager.GetString("018A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreMoveDelete.
        /// </summary>
        internal static string _018B {
            get {
                return ResourceManager.GetString("018B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMoveNumber.
        /// </summary>
        internal static string _018C {
            get {
                return ResourceManager.GetString("018C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMove.
        /// </summary>
        internal static string _018D {
            get {
                return ResourceManager.GetString("018D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableMoveDelete.
        /// </summary>
        internal static string _018F {
            get {
                return ResourceManager.GetString("018F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveItemStored.
        /// </summary>
        internal static string _0194 {
            get {
                return ResourceManager.GetString("0194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonRem.
        /// </summary>
        internal static string _01D3 {
            get {
                return ResourceManager.GetString("01D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreMoveRem.
        /// </summary>
        internal static string _01D5 {
            get {
                return ResourceManager.GetString("01D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonTrade.
        /// </summary>
        internal static string _01D8 {
            get {
                return ResourceManager.GetString("01D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeChosenPokemon.
        /// </summary>
        internal static string _01D9 {
            get {
                return ResourceManager.GetString("01D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopTrade.
        /// </summary>
        internal static string _01DA {
            get {
                return ResourceManager.GetString("01DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckRibbon.
        /// </summary>
        internal static string _01E0 {
            get {
                return ResourceManager.GetString("01E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveRibbon.
        /// </summary>
        internal static string _01E1 {
            get {
                return ResourceManager.GetString("01E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonRibbon.
        /// </summary>
        internal static string _01E3 {
            get {
                return ResourceManager.GetString("01E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBattleRecorder.
        /// </summary>
        internal static string _01E6 {
            get {
                return ResourceManager.GetString("01E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckVersion.
        /// </summary>
        internal static string _01EF {
            get {
                return ResourceManager.GetString("01EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxesNumber.
        /// </summary>
        internal static string _01FB {
            get {
                return ResourceManager.GetString("01FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreFriendParkResult.
        /// </summary>
        internal static string _01FF {
            get {
                return ResourceManager.GetString("01FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonMenuTrade.
        /// </summary>
        internal static string _0236 {
            get {
                return ResourceManager.GetString("0236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegendaryBattle.
        /// </summary>
        internal static string _024D {
            get {
                return ResourceManager.GetString("024D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartFriendPark.
        /// </summary>
        internal static string _0258 {
            get {
                return ResourceManager.GetString("0258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndFriendPark.
        /// </summary>
        internal static string _025E {
            get {
                return ResourceManager.GetString("025E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MecScript.
        /// </summary>
        internal static string _0261 {
            get {
                return ResourceManager.GetString("0261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakePhoto.
        /// </summary>
        internal static string _0267 {
            get {
                return ResourceManager.GetString("0267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAlbumPhoto.
        /// </summary>
        internal static string _026A {
            get {
                return ResourceManager.GetString("026A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckWildBattle2.
        /// </summary>
        internal static string _02BC {
            get {
                return ResourceManager.GetString("02BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WildBattle2.
        /// </summary>
        internal static string _02BD {
            get {
                return ResourceManager.GetString("02BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLowScreen.
        /// </summary>
        internal static string _02EA {
            get {
                return ResourceManager.GetString("02EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseLowScreen.
        /// </summary>
        internal static string _02EB {
            get {
                return ResourceManager.GetString("02EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLowYesNoBox.
        /// </summary>
        internal static string _02EC {
            get {
                return ResourceManager.GetString("02EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi4.
        /// </summary>
        internal static string _02ED {
            get {
                return ResourceManager.GetString("02ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi5.
        /// </summary>
        internal static string _02EE {
            get {
                return ResourceManager.GetString("02EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextScriptMulti4.
        /// </summary>
        internal static string _02EF {
            get {
                return ResourceManager.GetString("02EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMulti4.
        /// </summary>
        internal static string _02F0 {
            get {
                return ResourceManager.GetString("02F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeMomMoney.
        /// </summary>
        internal static string _0319 {
            get {
                return ResourceManager.GetString("0319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveMomMoney.
        /// </summary>
        internal static string _031A {
            get {
                return ResourceManager.GetString("031A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenMomMoneyBox.
        /// </summary>
        internal static string _031B {
            get {
                return ResourceManager.GetString("031B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMomMoneyBox.
        /// </summary>
        internal static string _031C {
            get {
                return ResourceManager.GetString("031C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMomMoneyNumber.
        /// </summary>
        internal static string _0346 {
            get {
                return ResourceManager.GetString("0346", resourceCulture);
            }
        }
    }
}
