//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_Map.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptNames", typeof(ScriptNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nop.
        /// </summary>
        internal static string _0000 {
            get {
                return ResourceManager.GetString("0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nop1.
        /// </summary>
        internal static string _0001 {
            get {
                return ResourceManager.GetString("0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return2.
        /// </summary>
        internal static string _0003 {
            get {
                return ResourceManager.GetString("0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string _0011 {
            get {
                return ResourceManager.GetString("0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If2.
        /// </summary>
        internal static string _0012 {
            get {
                return ResourceManager.GetString("0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallStandard.
        /// </summary>
        internal static string _0014 {
            get {
                return ResourceManager.GetString("0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string _0016 {
            get {
                return ResourceManager.GetString("0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string _001A {
            get {
                return ResourceManager.GetString("001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string _001B {
            get {
                return ResourceManager.GetString("001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareLastResultJump.
        /// </summary>
        internal static string _001C {
            get {
                return ResourceManager.GetString("001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareLastResultCall.
        /// </summary>
        internal static string _001D {
            get {
                return ResourceManager.GetString("001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearFlag.
        /// </summary>
        internal static string _001E {
            get {
                return ResourceManager.GetString("001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFlag.
        /// </summary>
        internal static string _001F {
            get {
                return ResourceManager.GetString("001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFlag.
        /// </summary>
        internal static string _0020 {
            get {
                return ResourceManager.GetString("0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetValue.
        /// </summary>
        internal static string _0023 {
            get {
                return ResourceManager.GetString("0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareVarsToByte.
        /// </summary>
        internal static string _0026 {
            get {
                return ResourceManager.GetString("0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVar.
        /// </summary>
        internal static string _0028 {
            get {
                return ResourceManager.GetString("0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyVar.
        /// </summary>
        internal static string _0029 {
            get {
                return ResourceManager.GetString("0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _002C {
            get {
                return ResourceManager.GetString("002C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message2.
        /// </summary>
        internal static string _002D {
            get {
                return ResourceManager.GetString("002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message3.
        /// </summary>
        internal static string _002F {
            get {
                return ResourceManager.GetString("002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitButton.
        /// </summary>
        internal static string _0031 {
            get {
                return ResourceManager.GetString("0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMessageOnKeyPress.
        /// </summary>
        internal static string _0034 {
            get {
                return ResourceManager.GetString("0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreezeMessageBox.
        /// </summary>
        internal static string _0035 {
            get {
                return ResourceManager.GetString("0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallMessageBox.
        /// </summary>
        internal static string _0036 {
            get {
                return ResourceManager.GetString("0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorMessageBox.
        /// </summary>
        internal static string _0037 {
            get {
                return ResourceManager.GetString("0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeMessageBox.
        /// </summary>
        internal static string _0038 {
            get {
                return ResourceManager.GetString("0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoMapMessageBox.
        /// </summary>
        internal static string _0039 {
            get {
                return ResourceManager.GetString("0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallMessageBoxText.
        /// </summary>
        internal static string _003A {
            get {
                return ResourceManager.GetString("003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string _003C {
            get {
                return ResourceManager.GetString("003C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesNoBox.
        /// </summary>
        internal static string _003E {
            get {
                return ResourceManager.GetString("003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitFor.
        /// </summary>
        internal static string _003F {
            get {
                return ResourceManager.GetString("003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        internal static string _0040 {
            get {
                return ResourceManager.GetString("0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi2.
        /// </summary>
        internal static string _0041 {
            get {
                return ResourceManager.GetString("0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextScriptMulti.
        /// </summary>
        internal static string _0042 {
            get {
                return ResourceManager.GetString("0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMulti.
        /// </summary>
        internal static string _0043 {
            get {
                return ResourceManager.GetString("0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi3.
        /// </summary>
        internal static string _0044 {
            get {
                return ResourceManager.GetString("0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextMessageScriptMulti.
        /// </summary>
        internal static string _0046 {
            get {
                return ResourceManager.GetString("0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiRow.
        /// </summary>
        internal static string _0048 {
            get {
                return ResourceManager.GetString("0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayFanfare.
        /// </summary>
        internal static string _0049 {
            get {
                return ResourceManager.GetString("0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayFanfare2.
        /// </summary>
        internal static string _004A {
            get {
                return ResourceManager.GetString("004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitFanfare.
        /// </summary>
        internal static string _004B {
            get {
                return ResourceManager.GetString("004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayCry.
        /// </summary>
        internal static string _004C {
            get {
                return ResourceManager.GetString("004C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitCry.
        /// </summary>
        internal static string _004D {
            get {
                return ResourceManager.GetString("004D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaySound.
        /// </summary>
        internal static string _004E {
            get {
                return ResourceManager.GetString("004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FadeDefaultMusic.
        /// </summary>
        internal static string _004F {
            get {
                return ResourceManager.GetString("004F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayMusic.
        /// </summary>
        internal static string _0050 {
            get {
                return ResourceManager.GetString("0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopMusic.
        /// </summary>
        internal static string _0051 {
            get {
                return ResourceManager.GetString("0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartMusic.
        /// </summary>
        internal static string _0052 {
            get {
                return ResourceManager.GetString("0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchMusic.
        /// </summary>
        internal static string _0054 {
            get {
                return ResourceManager.GetString("0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchMusic2.
        /// </summary>
        internal static string _005A {
            get {
                return ResourceManager.GetString("005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyMovement.
        /// </summary>
        internal static string _005E {
            get {
                return ResourceManager.GetString("005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMovement.
        /// </summary>
        internal static string _005F {
            get {
                return ResourceManager.GetString("005F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockAll.
        /// </summary>
        internal static string _0060 {
            get {
                return ResourceManager.GetString("0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseAll.
        /// </summary>
        internal static string _0061 {
            get {
                return ResourceManager.GetString("0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string _0062 {
            get {
                return ResourceManager.GetString("0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string _0063 {
            get {
                return ResourceManager.GetString("0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPeople.
        /// </summary>
        internal static string _0064 {
            get {
                return ResourceManager.GetString("0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemovePeople.
        /// </summary>
        internal static string _0065 {
            get {
                return ResourceManager.GetString("0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockCam.
        /// </summary>
        internal static string _0066 {
            get {
                return ResourceManager.GetString("0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacePlayer.
        /// </summary>
        internal static string _0068 {
            get {
                return ResourceManager.GetString("0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSpritePosition.
        /// </summary>
        internal static string _0069 {
            get {
                return ResourceManager.GetString("0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPersonPosition.
        /// </summary>
        internal static string _006B {
            get {
                return ResourceManager.GetString("006B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueFollow.
        /// </summary>
        internal static string _006C {
            get {
                return ResourceManager.GetString("006C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FollowHero.
        /// </summary>
        internal static string _006D {
            get {
                return ResourceManager.GetString("006D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopFollowHero.
        /// </summary>
        internal static string _006E {
            get {
                return ResourceManager.GetString("006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveMoney.
        /// </summary>
        internal static string _006F {
            get {
                return ResourceManager.GetString("006F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeMoney.
        /// </summary>
        internal static string _0070 {
            get {
                return ResourceManager.GetString("0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMoney.
        /// </summary>
        internal static string _0071 {
            get {
                return ResourceManager.GetString("0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMoney.
        /// </summary>
        internal static string _0072 {
            get {
                return ResourceManager.GetString("0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideMoney.
        /// </summary>
        internal static string _0073 {
            get {
                return ResourceManager.GetString("0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateMoney.
        /// </summary>
        internal static string _0074 {
            get {
                return ResourceManager.GetString("0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowCoins.
        /// </summary>
        internal static string _0075 {
            get {
                return ResourceManager.GetString("0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideCoins.
        /// </summary>
        internal static string _0076 {
            get {
                return ResourceManager.GetString("0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateCoins.
        /// </summary>
        internal static string _0077 {
            get {
                return ResourceManager.GetString("0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCoins.
        /// </summary>
        internal static string _0078 {
            get {
                return ResourceManager.GetString("0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveCoins.
        /// </summary>
        internal static string _0079 {
            get {
                return ResourceManager.GetString("0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeCoins.
        /// </summary>
        internal static string _007A {
            get {
                return ResourceManager.GetString("007A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeItem.
        /// </summary>
        internal static string _007B {
            get {
                return ResourceManager.GetString("007B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckStoreItem.
        /// </summary>
        internal static string _007C {
            get {
                return ResourceManager.GetString("007C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckItem.
        /// </summary>
        internal static string _007D {
            get {
                return ResourceManager.GetString("007D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckUndergroundPcStatus.
        /// </summary>
        internal static string _0085 {
            get {
                return ResourceManager.GetString("0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonParty.
        /// </summary>
        internal static string _0093 {
            get {
                return ResourceManager.GetString("0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePokemonParty.
        /// </summary>
        internal static string _0094 {
            get {
                return ResourceManager.GetString("0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPokemonPartyStored.
        /// </summary>
        internal static string _0095 {
            get {
                return ResourceManager.GetString("0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivePokemon.
        /// </summary>
        internal static string _0096 {
            get {
                return ResourceManager.GetString("0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveEgg.
        /// </summary>
        internal static string _0097 {
            get {
                return ResourceManager.GetString("0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMove.
        /// </summary>
        internal static string _0099 {
            get {
                return ResourceManager.GetString("0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPlaceStored.
        /// </summary>
        internal static string _009A {
            get {
                return ResourceManager.GetString("009A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallEnd.
        /// </summary>
        internal static string _00A1 {
            get {
                return ResourceManager.GetString("00A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC.
        /// </summary>
        internal static string _00A3 {
            get {
                return ResourceManager.GetString("00A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview.
        /// </summary>
        internal static string _00A5 {
            get {
                return ResourceManager.GetString("00A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DressPokemon.
        /// </summary>
        internal static string _00A6 {
            get {
                return ResourceManager.GetString("00A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayDressedPokemon.
        /// </summary>
        internal static string _00A7 {
            get {
                return ResourceManager.GetString("00A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayContestPokemon.
        /// </summary>
        internal static string _00A8 {
            get {
                return ResourceManager.GetString("00A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapsuleEditor.
        /// </summary>
        internal static string _00A9 {
            get {
                return ResourceManager.GetString("00A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SinnohMaps.
        /// </summary>
        internal static string _00AA {
            get {
                return ResourceManager.GetString("00AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoxPokemon.
        /// </summary>
        internal static string _00AB {
            get {
                return ResourceManager.GetString("00AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrawUnion.
        /// </summary>
        internal static string _00AC {
            get {
                return ResourceManager.GetString("00AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainerCaseUnion.
        /// </summary>
        internal static string _00AD {
            get {
                return ResourceManager.GetString("00AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeUnion.
        /// </summary>
        internal static string _00AE {
            get {
                return ResourceManager.GetString("00AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordMixingUnion.
        /// </summary>
        internal static string _00AF {
            get {
                return ResourceManager.GetString("00AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndGame.
        /// </summary>
        internal static string _00B0 {
            get {
                return ResourceManager.GetString("00B0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HallFameData.
        /// </summary>
        internal static string _00B1 {
            get {
                return ResourceManager.GetString("00B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC1.
        /// </summary>
        internal static string _00B3 {
            get {
                return ResourceManager.GetString("00B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseStarter.
        /// </summary>
        internal static string _00B4 {
            get {
                return ResourceManager.GetString("00B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePlayerName.
        /// </summary>
        internal static string _00BA {
            get {
                return ResourceManager.GetString("00BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonName.
        /// </summary>
        internal static string _00BB {
            get {
                return ResourceManager.GetString("00BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FadeScreen.
        /// </summary>
        internal static string _00BC {
            get {
                return ResourceManager.GetString("00BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetScreen.
        /// </summary>
        internal static string _00BD {
            get {
                return ResourceManager.GetString("00BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        internal static string _00BE {
            get {
                return ResourceManager.GetString("00BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RockClimbAnimation.
        /// </summary>
        internal static string _00BF {
            get {
                return ResourceManager.GetString("00BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurfAnimation.
        /// </summary>
        internal static string _00C0 {
            get {
                return ResourceManager.GetString("00C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterfallAnimation.
        /// </summary>
        internal static string _00C1 {
            get {
                return ResourceManager.GetString("00C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlyAnimation.
        /// </summary>
        internal static string _00C2 {
            get {
                return ResourceManager.GetString("00C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuxedo.
        /// </summary>
        internal static string _00C6 {
            get {
                return ResourceManager.GetString("00C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBike.
        /// </summary>
        internal static string _00C7 {
            get {
                return ResourceManager.GetString("00C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RideBike.
        /// </summary>
        internal static string _00C8 {
            get {
                return ResourceManager.GetString("00C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BerryHiroAnimation.
        /// </summary>
        internal static string _00CB {
            get {
                return ResourceManager.GetString("00CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopBerryHiroAnimation.
        /// </summary>
        internal static string _00CC {
            get {
                return ResourceManager.GetString("00CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableHero.
        /// </summary>
        internal static string _00CD {
            get {
                return ResourceManager.GetString("00CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableRival.
        /// </summary>
        internal static string _00CE {
            get {
                return ResourceManager.GetString("00CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAlter.
        /// </summary>
        internal static string _00CF {
            get {
                return ResourceManager.GetString("00CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariablePokemon.
        /// </summary>
        internal static string _00D0 {
            get {
                return ResourceManager.GetString("00D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableItem.
        /// </summary>
        internal static string _00D1 {
            get {
                return ResourceManager.GetString("00D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAttackItem.
        /// </summary>
        internal static string _00D3 {
            get {
                return ResourceManager.GetString("00D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableAttack.
        /// </summary>
        internal static string _00D4 {
            get {
                return ResourceManager.GetString("00D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableNumber.
        /// </summary>
        internal static string _00D5 {
            get {
                return ResourceManager.GetString("00D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableNickname.
        /// </summary>
        internal static string _00D6 {
            get {
                return ResourceManager.GetString("00D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableObject.
        /// </summary>
        internal static string _00D7 {
            get {
                return ResourceManager.GetString("00D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariableTrainer.
        /// </summary>
        internal static string _00D8 {
            get {
                return ResourceManager.GetString("00D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVarPokemonStored.
        /// </summary>
        internal static string _00DA {
            get {
                return ResourceManager.GetString("00DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVarHeroStored.
        /// </summary>
        internal static string _00DB {
            get {
                return ResourceManager.GetString("00DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVarRivalStored.
        /// </summary>
        internal static string _00DC {
            get {
                return ResourceManager.GetString("00DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVarAlterStored.
        /// </summary>
        internal static string _00DD {
            get {
                return ResourceManager.GetString("00DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreStarter.
        /// </summary>
        internal static string _00DE {
            get {
                return ResourceManager.GetString("00DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainerBattle.
        /// </summary>
        internal static string _00E5 {
            get {
                return ResourceManager.GetString("00E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTrainerBattle.
        /// </summary>
        internal static string _00E6 {
            get {
                return ResourceManager.GetString("00E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActLeagueBattlers.
        /// </summary>
        internal static string _00EA {
            get {
                return ResourceManager.GetString("00EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LostGoPokecenter.
        /// </summary>
        internal static string _00EB {
            get {
                return ResourceManager.GetString("00EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckLost.
        /// </summary>
        internal static string _00EC {
            get {
                return ResourceManager.GetString("00EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseFriend.
        /// </summary>
        internal static string _00F2 {
            get {
                return ResourceManager.GetString("00F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WirelessBattleWait.
        /// </summary>
        internal static string _00F3 {
            get {
                return ResourceManager.GetString("00F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonContest.
        /// </summary>
        internal static string _00F7 {
            get {
                return ResourceManager.GetString("00F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashContest.
        /// </summary>
        internal static string _0111 {
            get {
                return ResourceManager.GetString("0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndFlash.
        /// </summary>
        internal static string _0112 {
            get {
                return ResourceManager.GetString("0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowLinkCountRecord.
        /// </summary>
        internal static string _0116 {
            get {
                return ResourceManager.GetString("0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarpMapElevator.
        /// </summary>
        internal static string _011B {
            get {
                return ResourceManager.GetString("011B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFloor.
        /// </summary>
        internal static string _011C {
            get {
                return ResourceManager.GetString("011C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPositionAfterShip.
        /// </summary>
        internal static string _0120 {
            get {
                return ResourceManager.GetString("0120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WildBattle.
        /// </summary>
        internal static string _0124 {
            get {
                return ResourceManager.GetString("0124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarterBattle.
        /// </summary>
        internal static string _0125 {
            get {
                return ResourceManager.GetString("0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExplanationBattle.
        /// </summary>
        internal static string _0126 {
            get {
                return ResourceManager.GetString("0126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoneyTreeBattle.
        /// </summary>
        internal static string _0127 {
            get {
                return ResourceManager.GetString("0127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RandomBattle.
        /// </summary>
        internal static string _0129 {
            get {
                return ResourceManager.GetString("0129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteAutograph.
        /// </summary>
        internal static string _012B {
            get {
                return ResourceManager.GetString("012B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckDress.
        /// </summary>
        internal static string _012E {
            get {
                return ResourceManager.GetString("012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivePoketch.
        /// </summary>
        internal static string _0131 {
            get {
                return ResourceManager.GetString("0131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivatePoketchApp.
        /// </summary>
        internal static string _0133 {
            get {
                return ResourceManager.GetString("0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePoketchApp.
        /// </summary>
        internal static string _0134 {
            get {
                return ResourceManager.GetString("0134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectDecisionOther.
        /// </summary>
        internal static string _0143 {
            get {
                return ResourceManager.GetString("0143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemart.
        /// </summary>
        internal static string _0147 {
            get {
                return ResourceManager.GetString("0147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemart1.
        /// </summary>
        internal static string _0148 {
            get {
                return ResourceManager.GetString("0148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemart2.
        /// </summary>
        internal static string _0149 {
            get {
                return ResourceManager.GetString("0149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemart3.
        /// </summary>
        internal static string _014A {
            get {
                return ResourceManager.GetString("014A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefeatGoPokecenter.
        /// </summary>
        internal static string _014B {
            get {
                return ResourceManager.GetString("014B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckGender.
        /// </summary>
        internal static string _014D {
            get {
                return ResourceManager.GetString("014D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealPokemon.
        /// </summary>
        internal static string _014E {
            get {
                return ResourceManager.GetString("014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnionRoom.
        /// </summary>
        internal static string _0153 {
            get {
                return ResourceManager.GetString("0153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivatePokedex.
        /// </summary>
        internal static string _0158 {
            get {
                return ResourceManager.GetString("0158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveRunningShoes.
        /// </summary>
        internal static string _015A {
            get {
                return ResourceManager.GetString("015A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBadge.
        /// </summary>
        internal static string _015B {
            get {
                return ResourceManager.GetString("015B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableBadge.
        /// </summary>
        internal static string _015C {
            get {
                return ResourceManager.GetString("015C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableBadge.
        /// </summary>
        internal static string _015D {
            get {
                return ResourceManager.GetString("015D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrepareDoorAnimation.
        /// </summary>
        internal static string _0168 {
            get {
                return ResourceManager.GetString("0168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitAction.
        /// </summary>
        internal static string _0169 {
            get {
                return ResourceManager.GetString("0169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitClose.
        /// </summary>
        internal static string _016A {
            get {
                return ResourceManager.GetString("016A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenDoor.
        /// </summary>
        internal static string _016B {
            get {
                return ResourceManager.GetString("016B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDoor.
        /// </summary>
        internal static string _016C {
            get {
                return ResourceManager.GetString("016C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPartyNumber.
        /// </summary>
        internal static string _0177 {
            get {
                return ResourceManager.GetString("0177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenBerryPouch.
        /// </summary>
        internal static string _0178 {
            get {
                return ResourceManager.GetString("0178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOverworldPosition.
        /// </summary>
        internal static string _0186 {
            get {
                return ResourceManager.GetString("0186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOverworldMovement.
        /// </summary>
        internal static string _0188 {
            get {
                return ResourceManager.GetString("0188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseOverworld.
        /// </summary>
        internal static string _0189 {
            get {
                return ResourceManager.GetString("0189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDoorPassable.
        /// </summary>
        internal static string _018A {
            get {
                return ResourceManager.GetString("018A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDoorLocked.
        /// </summary>
        internal static string _018B {
            get {
                return ResourceManager.GetString("018B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowSavingClock.
        /// </summary>
        internal static string _018D {
            get {
                return ResourceManager.GetString("018D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideSavingClock.
        /// </summary>
        internal static string _018E {
            get {
                return ResourceManager.GetString("018E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonMenu.
        /// </summary>
        internal static string _0191 {
            get {
                return ResourceManager.GetString("0191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoosePokemonMenu2.
        /// </summary>
        internal static string _0192 {
            get {
                return ResourceManager.GetString("0192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePokemonMenu2.
        /// </summary>
        internal static string _0193 {
            get {
                return ResourceManager.GetString("0193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonInfo.
        /// </summary>
        internal static string _0195 {
            get {
                return ResourceManager.GetString("0195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorePokemonNumber.
        /// </summary>
        internal static string _0198 {
            get {
                return ResourceManager.GetString("0198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPartyNumber2.
        /// </summary>
        internal static string _019A {
            get {
                return ResourceManager.GetString("019A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EggAnimation.
        /// </summary>
        internal static string _01AC {
            get {
                return ResourceManager.GetString("01AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        internal static string _01B3 {
            get {
                return ResourceManager.GetString("01B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordList.
        /// </summary>
        internal static string _01B5 {
            get {
                return ResourceManager.GetString("01B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckHappiness.
        /// </summary>
        internal static string _01B9 {
            get {
                return ResourceManager.GetString("01B9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPosition.
        /// </summary>
        internal static string _01BD {
            get {
                return ResourceManager.GetString("01BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonParty2.
        /// </summary>
        internal static string _01C0 {
            get {
                return ResourceManager.GetString("01C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyPokemonHeight.
        /// </summary>
        internal static string _01C1 {
            get {
                return ResourceManager.GetString("01C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVariablePokemonHeight.
        /// </summary>
        internal static string _01C2 {
            get {
                return ResourceManager.GetString("01C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparePokemonHeight.
        /// </summary>
        internal static string _01C3 {
            get {
                return ResourceManager.GetString("01C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonHeight.
        /// </summary>
        internal static string _01C4 {
            get {
                return ResourceManager.GetString("01C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveInfo.
        /// </summary>
        internal static string _01C6 {
            get {
                return ResourceManager.GetString("01C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreMove.
        /// </summary>
        internal static string _01C7 {
            get {
                return ResourceManager.GetString("01C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMove.
        /// </summary>
        internal static string _01C9 {
            get {
                return ResourceManager.GetString("01C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BerryPoffin.
        /// </summary>
        internal static string _01D7 {
            get {
                return ResourceManager.GetString("01D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattleRoomResult.
        /// </summary>
        internal static string _01D9 {
            get {
                return ResourceManager.GetString("01D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSinnohPokedex.
        /// </summary>
        internal static string _01E8 {
            get {
                return ResourceManager.GetString("01E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckNationalPokedex.
        /// </summary>
        internal static string _01E9 {
            get {
                return ResourceManager.GetString("01E9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowSinnohSheet.
        /// </summary>
        internal static string _01EA {
            get {
                return ResourceManager.GetString("01EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowNationalSheet.
        /// </summary>
        internal static string _01EB {
            get {
                return ResourceManager.GetString("01EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFossil.
        /// </summary>
        internal static string _01F1 {
            get {
                return ResourceManager.GetString("01F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonLevel.
        /// </summary>
        internal static string _01F6 {
            get {
                return ResourceManager.GetString("01F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarpLastElevator.
        /// </summary>
        internal static string _0204 {
            get {
                return ResourceManager.GetString("0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonet.
        /// </summary>
        internal static string _0205 {
            get {
                return ResourceManager.GetString("0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreatMarshBynocule.
        /// </summary>
        internal static string _0206 {
            get {
                return ResourceManager.GetString("0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonPicture.
        /// </summary>
        internal static string _0208 {
            get {
                return ResourceManager.GetString("0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidePicture.
        /// </summary>
        internal static string _0209 {
            get {
                return ResourceManager.GetString("0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMove.
        /// </summary>
        internal static string _0221 {
            get {
                return ResourceManager.GetString("0221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeachMove.
        /// </summary>
        internal static string _0224 {
            get {
                return ResourceManager.GetString("0224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckTeachMove.
        /// </summary>
        internal static string _0225 {
            get {
                return ResourceManager.GetString("0225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPokemonTrade.
        /// </summary>
        internal static string _0228 {
            get {
                return ResourceManager.GetString("0228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeChosenPokemon.
        /// </summary>
        internal static string _0229 {
            get {
                return ResourceManager.GetString("0229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopTrade.
        /// </summary>
        internal static string _022A {
            get {
                return ResourceManager.GetString("022A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecideRules.
        /// </summary>
        internal static string _0239 {
            get {
                return ResourceManager.GetString("0239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealPokemonAnimation.
        /// </summary>
        internal static string _023B {
            get {
                return ResourceManager.GetString("023B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipAnimation.
        /// </summary>
        internal static string _023D {
            get {
                return ResourceManager.GetString("023D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhraseBox1W.
        /// </summary>
        internal static string _0243 {
            get {
                return ResourceManager.GetString("0243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhraseBox2W.
        /// </summary>
        internal static string _0244 {
            get {
                return ResourceManager.GetString("0244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPhraseBoxInput.
        /// </summary>
        internal static string _0249 {
            get {
                return ResourceManager.GetString("0249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreparePcAnimation.
        /// </summary>
        internal static string _024B {
            get {
                return ResourceManager.GetString("024B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenPcAnimation.
        /// </summary>
        internal static string _024C {
            get {
                return ResourceManager.GetString("024C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosePcAnimation.
        /// </summary>
        internal static string _024D {
            get {
                return ResourceManager.GetString("024D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckLottoNumber.
        /// </summary>
        internal static string _024E {
            get {
                return ResourceManager.GetString("024E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareLottoNumber.
        /// </summary>
        internal static string _024F {
            get {
                return ResourceManager.GetString("024F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxesNumber.
        /// </summary>
        internal static string _0252 {
            get {
                return ResourceManager.GetString("0252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SprtSave.
        /// </summary>
        internal static string _0257 {
            get {
                return ResourceManager.GetString("0257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetSprtSave.
        /// </summary>
        internal static string _0258 {
            get {
                return ResourceManager.GetString("0258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElevLgAnimation.
        /// </summary>
        internal static string _0259 {
            get {
                return ResourceManager.GetString("0259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAccessories.
        /// </summary>
        internal static string _0261 {
            get {
                return ResourceManager.GetString("0261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokecasino.
        /// </summary>
        internal static string _0267 {
            get {
                return ResourceManager.GetString("0267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnownMessageBox.
        /// </summary>
        internal static string _026D {
            get {
                return ResourceManager.GetString("026D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThankNameInsert.
        /// </summary>
        internal static string _0271 {
            get {
                return ResourceManager.GetString("0271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeagueCastleView.
        /// </summary>
        internal static string _027A {
            get {
                return ResourceManager.GetString("027A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonPartyPicture.
        /// </summary>
        internal static string _028C {
            get {
                return ResourceManager.GetString("028C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFirstTimeChampion.
        /// </summary>
        internal static string _028F {
            get {
                return ResourceManager.GetString("028F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowBattlePointsBox.
        /// </summary>
        internal static string _0294 {
            get {
                return ResourceManager.GetString("0294", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideBattlePointsBox.
        /// </summary>
        internal static string _0295 {
            get {
                return ResourceManager.GetString("0295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceMulti.
        /// </summary>
        internal static string _029D {
            get {
                return ResourceManager.GetString("029D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiddenMachineEffect.
        /// </summary>
        internal static string _029E {
            get {
                return ResourceManager.GetString("029E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraBumpEffect.
        /// </summary>
        internal static string _029F {
            get {
                return ResourceManager.GetString("029F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleBattle.
        /// </summary>
        internal static string _02A0 {
            get {
                return ResourceManager.GetString("02A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyMovement2.
        /// </summary>
        internal static string _02A1 {
            get {
                return ResourceManager.GetString("02A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseTradePokemon.
        /// </summary>
        internal static string _02A5 {
            get {
                return ResourceManager.GetString("02A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparePhraseBoxInput.
        /// </summary>
        internal static string _02AA {
            get {
                return ResourceManager.GetString("02AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateMysteryGift.
        /// </summary>
        internal static string _02AC {
            get {
                return ResourceManager.GetString("02AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckWildBattle2.
        /// </summary>
        internal static string _02BC {
            get {
                return ResourceManager.GetString("02BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WildBattle2.
        /// </summary>
        internal static string _02BD {
            get {
                return ResourceManager.GetString("02BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BikeRide.
        /// </summary>
        internal static string _02BF {
            get {
                return ResourceManager.GetString("02BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowSaveBox.
        /// </summary>
        internal static string _02C1 {
            get {
                return ResourceManager.GetString("02C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideSaveBox.
        /// </summary>
        internal static string _02C2 {
            get {
                return ResourceManager.GetString("02C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpinTradeUnion.
        /// </summary>
        internal static string _02C6 {
            get {
                return ResourceManager.GetString("02C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckVersionGame.
        /// </summary>
        internal static string _02C7 {
            get {
                return ResourceManager.GetString("02C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloralClockAnimation.
        /// </summary>
        internal static string _02CA {
            get {
                return ResourceManager.GetString("02CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalEffect.
        /// </summary>
        internal static string _0328 {
            get {
                return ResourceManager.GetString("0328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayFloor.
        /// </summary>
        internal static string _0347 {
            get {
                return ResourceManager.GetString("0347", resourceCulture);
            }
        }
    }
}
