//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources.ScriptsV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNamesWBW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNamesWBW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptsV.ScriptNamesWBW", typeof(ScriptNamesWBW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006B.
        /// </summary>
        internal static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004A.
        /// </summary>
        internal static string AngryMessage {
            get {
                return ResourceManager.GetString("AngryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0064.
        /// </summary>
        internal static string ApplyMovement {
            get {
                return ResourceManager.GetString("ApplyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0038.
        /// </summary>
        internal static string BubbleMessage {
            get {
                return ResourceManager.GetString("BubbleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001C.
        /// </summary>
        internal static string CallStandard {
            get {
                return ResourceManager.GetString("CallStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0024.
        /// </summary>
        internal static string ClearFlag {
            get {
                return ResourceManager.GetString("ClearFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000A.
        /// </summary>
        internal static string ClearVariable {
            get {
                return ResourceManager.GetString("ClearVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004B.
        /// </summary>
        internal static string CloseAngryMessage {
            get {
                return ResourceManager.GetString("CloseAngryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0039.
        /// </summary>
        internal static string CloseBubbleMessage {
            get {
                return ResourceManager.GetString("CloseBubbleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003E.
        /// </summary>
        internal static string CloseMessageOnKeyPress {
            get {
                return ResourceManager.GetString("CloseMessageOnKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003F.
        /// </summary>
        internal static string CloseMessageOnKeyPress2 {
            get {
                return ResourceManager.GetString("CloseMessageOnKeyPress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0074.
        /// </summary>
        internal static string FacePlayer {
            get {
                return ResourceManager.GetString("FacePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B3.
        /// </summary>
        internal static string FadeScreen {
            get {
                return ResourceManager.GetString("FadeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0104.
        /// </summary>
        internal static string HealPokemon {
            get {
                return ResourceManager.GetString("HealPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001F.
        /// </summary>
        internal static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001E.
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002E.
        /// </summary>
        internal static string LockAll {
            get {
                return ResourceManager.GetString("LockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003C.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003D.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0033.
        /// </summary>
        internal static string MusicalMessage {
            get {
                return ResourceManager.GetString("MusicalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        internal static string PauseEnd {
            get {
                return ResourceManager.GetString("PauseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AB.
        /// </summary>
        internal static string PlayCry {
            get {
                return ResourceManager.GetString("PlayCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A9.
        /// </summary>
        internal static string PlayFanfare {
            get {
                return ResourceManager.GetString("PlayFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00A6.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008B.
        /// </summary>
        internal static string PlayTrainerMusic {
            get {
                return ResourceManager.GetString("PlayTrainerMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002F.
        /// </summary>
        internal static string ReleaseAll {
            get {
                return ResourceManager.GetString("ReleaseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006C.
        /// </summary>
        internal static string RemovePeople {
            get {
                return ResourceManager.GetString("RemovePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00B4.
        /// </summary>
        internal static string ResetScreen {
            get {
                return ResourceManager.GetString("ResetScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001D.
        /// </summary>
        internal static string ReturnStandard {
            get {
                return ResourceManager.GetString("ReturnStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0023.
        /// </summary>
        internal static string SetFlag {
            get {
                return ResourceManager.GetString("SetFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006D.
        /// </summary>
        internal static string SetOverworldPosition {
            get {
                return ResourceManager.GetString("SetOverworldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010.
        /// </summary>
        internal static string StoreFlag {
            get {
                return ResourceManager.GetString("StoreFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0094.
        /// </summary>
        internal static string TrainerBattle {
            get {
                return ResourceManager.GetString("TrainerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0032.
        /// </summary>
        internal static string WaitButton {
            get {
                return ResourceManager.GetString("WaitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AC.
        /// </summary>
        internal static string WaitCry {
            get {
                return ResourceManager.GetString("WaitCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00AA.
        /// </summary>
        internal static string WaitFanfare {
            get {
                return ResourceManager.GetString("WaitFanfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0030.
        /// </summary>
        internal static string WaitMoment {
            get {
                return ResourceManager.GetString("WaitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0065.
        /// </summary>
        internal static string WaitMovement {
            get {
                return ResourceManager.GetString("WaitMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0174.
        /// </summary>
        internal static string WildBattle {
            get {
                return ResourceManager.GetString("WildBattle", resourceCulture);
            }
        }
    }
}
