//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Resources.ScriptsV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptNamesBWJ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptNamesBWJ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resources.ScriptsV.ScriptNamesBWJ", typeof(ScriptNamesBWJ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PauseEnd.
        /// </summary>
        internal static string _0003 {
            get {
                return ResourceManager.GetString("0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string _0004 {
            get {
                return ResourceManager.GetString("0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string _0005 {
            get {
                return ResourceManager.GetString("0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearVariable.
        /// </summary>
        internal static string _000A {
            get {
                return ResourceManager.GetString("000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreFlag.
        /// </summary>
        internal static string _0010 {
            get {
                return ResourceManager.GetString("0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallStandard.
        /// </summary>
        internal static string _001C {
            get {
                return ResourceManager.GetString("001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnStandard.
        /// </summary>
        internal static string _001D {
            get {
                return ResourceManager.GetString("001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string _001E {
            get {
                return ResourceManager.GetString("001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string _001F {
            get {
                return ResourceManager.GetString("001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFlag.
        /// </summary>
        internal static string _0023 {
            get {
                return ResourceManager.GetString("0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearFlag.
        /// </summary>
        internal static string _0024 {
            get {
                return ResourceManager.GetString("0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockAll.
        /// </summary>
        internal static string _002E {
            get {
                return ResourceManager.GetString("002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseAll.
        /// </summary>
        internal static string _002F {
            get {
                return ResourceManager.GetString("002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMoment.
        /// </summary>
        internal static string _0030 {
            get {
                return ResourceManager.GetString("0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitButton.
        /// </summary>
        internal static string _0032 {
            get {
                return ResourceManager.GetString("0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicalMessage.
        /// </summary>
        internal static string _0033 {
            get {
                return ResourceManager.GetString("0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BubbleMessage.
        /// </summary>
        internal static string _0038 {
            get {
                return ResourceManager.GetString("0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseBubbleMessage.
        /// </summary>
        internal static string _0039 {
            get {
                return ResourceManager.GetString("0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _003C {
            get {
                return ResourceManager.GetString("003C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message2.
        /// </summary>
        internal static string _003D {
            get {
                return ResourceManager.GetString("003D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMessageOnKeyPress.
        /// </summary>
        internal static string _003E {
            get {
                return ResourceManager.GetString("003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseMessageOnKeyPress2.
        /// </summary>
        internal static string _003F {
            get {
                return ResourceManager.GetString("003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngryMessage.
        /// </summary>
        internal static string _004A {
            get {
                return ResourceManager.GetString("004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseAngryMessage.
        /// </summary>
        internal static string _004B {
            get {
                return ResourceManager.GetString("004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyMovement.
        /// </summary>
        internal static string _0060 {
            get {
                return ResourceManager.GetString("0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitMovement.
        /// </summary>
        internal static string _0061 {
            get {
                return ResourceManager.GetString("0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPeople.
        /// </summary>
        internal static string _0067 {
            get {
                return ResourceManager.GetString("0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemovePeople.
        /// </summary>
        internal static string _0068 {
            get {
                return ResourceManager.GetString("0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOverworldPosition.
        /// </summary>
        internal static string _0069 {
            get {
                return ResourceManager.GetString("0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacePlayer.
        /// </summary>
        internal static string _0070 {
            get {
                return ResourceManager.GetString("0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayTrainerMusic.
        /// </summary>
        internal static string _0087 {
            get {
                return ResourceManager.GetString("0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainerBattle.
        /// </summary>
        internal static string _0090 {
            get {
                return ResourceManager.GetString("0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaySound.
        /// </summary>
        internal static string _00A2 {
            get {
                return ResourceManager.GetString("00A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayFanfare.
        /// </summary>
        internal static string _00A5 {
            get {
                return ResourceManager.GetString("00A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitFanfare.
        /// </summary>
        internal static string _00A6 {
            get {
                return ResourceManager.GetString("00A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayCry.
        /// </summary>
        internal static string _00A7 {
            get {
                return ResourceManager.GetString("00A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitCry.
        /// </summary>
        internal static string _00A8 {
            get {
                return ResourceManager.GetString("00A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FadeScreen.
        /// </summary>
        internal static string _00AF {
            get {
                return ResourceManager.GetString("00AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetScreen.
        /// </summary>
        internal static string _00B0 {
            get {
                return ResourceManager.GetString("00B0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealPokemon.
        /// </summary>
        internal static string _0100 {
            get {
                return ResourceManager.GetString("0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WildBattle.
        /// </summary>
        internal static string _0170 {
            get {
                return ResourceManager.GetString("0170", resourceCulture);
            }
        }
    }
}
