name: DSPRE Build 
 
on: [push]
 
env:
  SOLUTION_FILE_PATH: DS_Map.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} 
    
    - name: Zip Release Files
      run: Compress-Archive ${{env.GITHUB_WORKSPACE}}DS_Map\bin\Release ${{env.GITHUB_WORKSPACE}}\DSPRE-${{ github.ref }}-beta-canary.zip

    - name: Changelog
      uses: Bullrich/generate-release-changelog@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}
        

    - name: Release with Notes
      uses: softprops/action-gh-release@v2
      with:
        release_name: DSPRE Beta Canary Build v${{ github.ref }}
        body: | 
            ${{ steps.Changelog.outputs.changelog }}
        files: ${{env.GITHUB_WORKSPACE}}\DSPRE-${{ github.ref }}-beta-canary.zip
        token: ${{ secrets.GITHUB_TOKEN }}