name: DSPRE Build 
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore DS_Map.sln
 
    - name: Build and Publish DSPRE Reloaded
      run: msbuild DS_Map.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: DSPRE_Reloaded
        path: bin\Release\